# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2026-03-10 13:36

import uuid
import functools

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("cm", "0001_initial"),
        ("cm", "0002_auto_20180801_1117"),
        ("cm", "0003_auto_20180829_1020"),
        ("cm", "0004_auto_20180914_1042"),
        ("cm", "0005_auto_20180928_0945"),
        ("cm", "0006_auto_20181009_1135"),
        ("cm", "0007_auto_20181023_1048"),
        ("cm", "0008_auto_20181107_1216"),
        ("cm", "0009_auto_20181113_1112"),
        ("cm", "0010_auto_20181212_1213"),
        ("cm", "0011_auto_20181220_1327"),
        ("cm", "0012_auto_20181226_0926"),
        ("cm", "0013_auto_20190116_1143"),
        ("cm", "0014_auto_20190124_1344"),
        ("cm", "0015_auto_20190128_1142"),
        ("cm", "0016_auto_20190218_1214"),
        ("cm", "0017_auto_20190220_1137"),
        ("cm", "0018_auto_20190220_1101"),
        ("cm", "0019_auto_20190314_1321"),
        ("cm", "0020_auto_20190321_1126"),
        ("cm", "0021_auto_20190607_1027"),
        ("cm", "0022_auto_20190620_1251"),
        ("cm", "0023_auto_20190624_1441"),
        ("cm", "0024_auto_20190715_1548"),
        ("cm", "0025_auto_20190719_1036"),
        ("cm", "0026_auto_20190805_1442"),
        ("cm", "0027_auto_20190809_1134"),
        ("cm", "0028_auto_20190813_1005"),
        ("cm", "0029_auto_20190814_1306"),
        ("cm", "0030_auto_20190820_1600"),
        ("cm", "0031_auto_20190926_1600"),
        ("cm", "0032_auto_20191015_1600"),
        ("cm", "0033_auto_20191023_1459"),
        ("cm", "0034_auto_20191029_1041"),
        ("cm", "0035_auto_20191031_1600"),
        ("cm", "0036_auto_20191111_1109"),
        ("cm", "0037_auto_20191120_1600"),
        ("cm", "0038_auto_20191119_1200"),
        ("cm", "0039_auto_20191203_0909"),
        ("cm", "0040_auto_20191218_1358"),
        ("cm", "0041_auto_20191220_1338"),
        ("cm", "0043_auto_20200109_1600"),
        ("cm", "0044_auto_20200115_1058"),
        ("cm", "0045_auto_20200117_1253"),
        ("cm", "0046_auto_20200120_1417"),
        ("cm", "0047_auto_20200210_1152"),
        ("cm", "0048_auto_20200228_1032"),
        ("cm", "0049_auto_20200330_1209"),
        ("cm", "0050_role"),
        ("cm", "0051_auto_20200403_0825"),
        ("cm", "0052_tasklog_attr"),
        ("cm", "0053_auto_20200415_1247"),
        ("cm", "0054_social_superuser"),
        ("cm", "0055_auto_20200424_1241"),
        ("cm", "0056_auto_20200714_0741"),
        ("cm", "0057_auto_20200831_1055"),
        ("cm", "0058_encrypt_passwords"),
        ("cm", "0059_auto_20200904_0910"),
        ("cm", "0060_auto_20201201_1122"),
        ("cm", "0061_auto_20201208_1250"),
        ("cm", "0062_auto_20201225_0949"),
        ("cm", "0063_tasklog_verbose"),
        ("cm", "0064_auto_20210210_1532"),
        ("cm", "0065_auto_20210220_0902"),
        ("cm", "0066_auto_20210427_0853"),
        ("cm", "0067_tasklog_object_type"),
        ("cm", "0068_alter_tasklog_action"),
        ("cm", "0069_auto_20210607_1125"),
        ("cm", "0070_lock_refactoring"),
        ("cm", "0071_messagetemplate"),
        ("cm", "0072_multi_state"),
        ("cm", "0073_issues_refactoring"),
        ("cm", "0074_auto_20210903_0957"),
        ("cm", "0075_actions_multistate"),
        ("cm", "0076_auto_20211013_1250"),
        ("cm", "0077_job_lock_message_tpl"),
        ("cm", "0078_alter_groupconfig_name"),
        ("cm", "0079_concernitem_cause"),
        ("cm", "0080_subaction_multi_states"),
        ("cm", "0081_auto_20220114_1246"),
        ("cm", "0082_remove_role"),
        ("cm", "0083_add_product_category"),
        ("cm", "0084_ansible_venv"),
        ("cm", "0085_add_action_to_upgrade"),
        ("cm", "0086_set_mitogen_to_false"),
        ("cm", "0087_maintenance_mode"),
        ("cm", "0088_fix_group_keys_structure"),
        ("cm", "0089_tasklog_post_upgrade_hc_map"),
        ("cm", "0090_rm_background_tasks_app"),
        ("cm", "0091_migrate_adcm_logrotate_config"),
        ("cm", "0092_auto_20220906_0957"),
        ("cm", "0093_auto_20220928_0556"),
        ("cm", "0094_increase_max_length"),
        ("cm", "0095_JobStatus"),
        ("cm", "0096_auto_20221101_1010"),
        ("cm", "0097_auto_20221109_1238"),
        ("cm", "0098_auto_20221115_1255"),
        ("cm", "0099_alter_adcm_concerns_alter_cluster_concerns_and_more"),
        ("cm", "0100_subaction_allow_terminate"),
        ("cm", "0101_delete_dummydata"),
        ("cm", "0102_auto_20230119_0755"),
        ("cm", "0103_auto_20230131_0946"),
        ("cm", "0104_auto_20230213_1132"),
        ("cm", "0105_auto_20230220_0800"),
        ("cm", "0106_set_nginx_rotate_config_to_defaults"),
        ("cm", "0107_add_display_name_field_to_upgrade"),
        ("cm", "0108_add_restore_hc_on_fail_field_to_task"),
        ("cm", "0109_message_template_requires_service"),
        ("cm", "0110_message_template_required"),
        ("cm", "0111_allow_flag_functionality"),
        ("cm", "0112_bundle_signature_status"),
        ("cm", "0113_mm_lower"),
        ("cm", "0114_adcm_uuid"),
        ("cm", "0115_auto_20231025_1823"),
        ("cm", "0116_fix_null_jsonfield"),
        ("cm", "0117_autonomous_joblogs"),
        ("cm", "0118_post_autonomous_joblogs"),
        ("cm", "0119_extract_sub_actions_from_actions"),
        ("cm", "0120_adjust_paths"),
        ("cm", "0121_delete_MessageTemplate"),
        ("cm", "0122_change_concern_item"),
        ("cm", "0123_flag_autogeneration_object"),
        ("cm", "0124_add_action_scripts_jinja_field"),
        ("cm", "0125_simplify_defaults"),
        ("cm", "0126_add_ansible_config"),
        ("cm", "0127_action_host_group"),
        ("cm", "0128_activate_statistics_collection"),
        ("cm", "0129_auto_20240904_1045"),
        ("cm", "0130_prepare_to_rename_models"),
        ("cm", "0131_rename_models"),
        ("cm", "0132_restore_FKs_after_models_renaming"),
        ("cm", "0133_add_is_blocking_and_index_to_tasks"),
        ("cm", "0134_bundle_bundle_lower_name_idx_and_more"),
        ("cm", "0135_remove_stale_ansibleconfig_actionhostgroup_entries"),
        ("cm", "0136_prototypeconfig_ansible_options_and_more"),
        ("cm", "0137_remove_tasklog_restore_hc_on_fail"),
        ("cm", "0138_extend_job_statuses_for_scheduler"),
        ("cm", "0139_add_task_executor_field"),
        ("cm", "0140_config_revision"),
        ("cm", "0141_alter_cluster_before_upgrade_and_more"),
        ("cm", "0142_action_wizard_template_and_process"),
        ("cm", "0143_alter_concernitem_cause"),
        ("cm", "0144_host_original_alter_host_fqdn_and_more"),
        ("cm", "0145_alter_stageaction_unique_together_and_more"),
        ("cm", "0146_cluster_uuid_component_uuid_host_uuid_service_uuid"),
        ("cm", "0147_action_config_template_action_scripts_template_and_more"),
        ("cm", "0148_tasklog_description"),
        ("cm", "0149_processstepinput_mapping"),
        ("cm", "0150_migrate_empty_string_secrets"),
        ("cm", "0151_release_2_10_0"),
    ]
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("ui_options", models.JSONField(default=dict)),
                ("type", models.CharField(choices=[("task", "task"), ("job", "job")], max_length=1000)),
                ("state_available", models.JSONField(default=list)),
                ("state_unavailable", models.JSONField(default=list)),
                ("state_on_success", models.CharField(blank=True, max_length=1000)),
                ("state_on_fail", models.CharField(blank=True, max_length=1000)),
                ("multi_state_available", models.JSONField(default=functools.partial(str, *("any",)))),
                ("multi_state_unavailable", models.JSONField(default=list)),
                ("multi_state_on_success_set", models.JSONField(default=list)),
                ("multi_state_on_success_unset", models.JSONField(default=list)),
                ("multi_state_on_fail_set", models.JSONField(default=list)),
                ("multi_state_on_fail_unset", models.JSONField(default=list)),
                ("hostcomponentmap", models.JSONField(default=list)),
                ("allow_to_terminate", models.BooleanField(default=False)),
                ("partial_execution", models.BooleanField(default=False)),
                ("host_action", models.BooleanField(default=False)),
                ("allow_for_action_host_group", models.BooleanField(default=False)),
                ("allow_in_maintenance_mode", models.BooleanField(default=False)),
                ("wizard_template", models.JSONField(default=None, null=True)),
                ("config_jinja", models.CharField(blank=True, max_length=1000, null=True)),
                ("config_template", models.JSONField(default=None, null=True)),
                ("scripts_jinja", models.CharField(blank=True, default="", max_length=512)),
                ("scripts_template", models.JSONField(default=None, null=True)),
                ("_venv", models.CharField(db_column="venv", default="default", max_length=1000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfigLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config", models.JSONField(default=dict)),
                ("attr", models.JSONField(default=dict)),
                ("date", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("script", models.CharField(max_length=1000)),
                (
                    "script_type",
                    models.CharField(
                        choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")],
                        max_length=1000,
                    ),
                ),
                ("state_on_fail", models.CharField(blank=True, max_length=1000)),
                ("multi_state_on_fail_set", models.JSONField(default=list)),
                ("multi_state_on_fail_unset", models.JSONField(default=list)),
                ("params", models.JSONField(default=dict)),
                ("allow_to_terminate", models.BooleanField(default=False)),
                ("pid", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("revoked", "revoked"),
                            ("created", "created"),
                            ("scheduled", "scheduled"),
                            ("queued", "queued"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("running", "running"),
                            ("locked", "locked"),
                            ("aborted", "aborted"),
                            ("broken", "broken"),
                        ],
                        default="created",
                        max_length=1000,
                    ),
                ),
                ("start_date", models.DateTimeField(default=None, null=True)),
                ("finish_date", models.DateTimeField(db_index=True, default=None, null=True)),
                ("objects_related_configs", models.JSONField(default=None, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ObjectConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current", models.PositiveIntegerField()),
                ("previous", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=1000, unique=True)),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("login", models.CharField(max_length=1000, unique=True)),
                ("profile", models.JSONField(default=str)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConcernItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("lock", "lock"), ("issue", "issue"), ("flag", "flag")], default="lock", max_length=100
                    ),
                ),
                ("name", models.CharField(default="", max_length=1000)),
                ("reason", models.JSONField(default=dict)),
                ("blocking", models.BooleanField(default=True)),
                ("owner_id", models.PositiveIntegerField()),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("config", "config"),
                            ("job", "job"),
                            ("host-component", "host-component"),
                            ("import", "import"),
                            ("service", "service"),
                            ("requirement", "requirement"),
                            ("configuring_process", "configuring_process"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "owner_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("_multi_state", models.JSONField(db_column="multi_state", default=dict)),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("description", models.TextField(blank=True)),
                ("before_upgrade", models.JSONField(default=functools.partial(dict, *((("state", None),),)))),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, related_name="%(class)s_entities", to="cm.concernitem"),
                ),
                (
                    "config",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfigRevision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("configlog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.configlog")),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("_multi_state", models.JSONField(db_column="multi_state", default=dict)),
                ("fqdn", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "maintenance_mode",
                    models.CharField(
                        choices=[("on", "on"), ("off", "off"), ("changing", "changing")], default="off", max_length=1000
                    ),
                ),
                ("before_upgrade", models.JSONField(default=functools.partial(dict, *((("state", None),),)))),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "cluster",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.cluster"
                    ),
                ),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, related_name="%(class)s_entities", to="cm.concernitem"),
                ),
                (
                    "original",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicates",
                        to="cm.host",
                    ),
                ),
                (
                    "config",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionHostGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=255)),
                (
                    "object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("hosts", models.ManyToManyField(to="cm.host")),
            ],
        ),
        migrations.CreateModel(
            name="HostInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.JSONField()),
                ("hash", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now=True)),
                ("host", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cm.host")),
            ],
        ),
        migrations.CreateModel(
            name="GroupCheckLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                ("result", models.BooleanField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.joblog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("message", models.TextField()),
                ("result", models.BooleanField()),
                (
                    "group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.groupchecklog"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.joblog"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LogStorage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(default="")),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("stdout", "stdout"), ("stderr", "stderr"), ("check", "check"), ("custom", "custom")],
                        max_length=1000,
                    ),
                ),
                ("format", models.CharField(choices=[("txt", "txt"), ("json", "json")], max_length=1000)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.joblog")),
            ],
        ),
        migrations.AddField(
            model_name="configlog",
            name="obj_ref",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
        ),
        migrations.CreateModel(
            name="ConfigHostGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                (
                    "object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("hosts", models.ManyToManyField(blank=True, related_name="config_host_group", to="cm.host")),
                (
                    "config",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_host_group",
                        to="cm.objectconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_id", models.PositiveIntegerField(default=0)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("adcm", "adcm"),
                            ("cluster", "cluster"),
                            ("service", "service"),
                            ("component", "component"),
                            ("provider", "provider"),
                            ("host", "host"),
                            ("action-host-group", "action-host-group"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("owner_id", models.PositiveIntegerField(default=0)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("cluster", "cluster"), ("service", "service"), ("component", "component")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("flow_spec", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sync_key", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[("created", "created"), ("broken", "broken"), ("completed", "completed")],
                        default="created",
                        max_length=100,
                    ),
                ),
                ("action", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.action")),
            ],
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("configuration", "configuration"),
                            ("mapping", "mapping"),
                            ("operation", "operation"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("stage", models.CharField(default="", max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("display_name", models.CharField(max_length=150)),
                ("step_spec", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("broken", "broken"),
                        ],
                        default="created",
                        max_length=100,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="cm.process"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="process",
            name="current_step",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_process",
                to="cm.processstep",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="last_completed_step",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_completed_for_process",
                to="cm.processstep",
            ),
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("version", models.CharField(max_length=1000)),
                ("edition", models.CharField(default="community", max_length=1000)),
                ("hash", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "signature_status",
                    models.CharField(
                        choices=[("valid", "valid"), ("invalid", "invalid"), ("absent", "absent")],
                        default="absent",
                        max_length=10,
                    ),
                ),
                ("contract_version", models.CharField(default="1.0", max_length=10)),
                (
                    "category",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to="cm.productcategory"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prototype",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("adcm", "adcm"),
                            ("cluster", "cluster"),
                            ("service", "service"),
                            ("component", "component"),
                            ("provider", "provider"),
                            ("host", "host"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("path", models.CharField(default="", max_length=1000)),
                ("name", models.CharField(max_length=1000)),
                (
                    "license",
                    models.CharField(
                        choices=[("absent", "absent"), ("accepted", "accepted"), ("unaccepted", "unaccepted")],
                        default="absent",
                        max_length=1000,
                    ),
                ),
                ("license_path", models.CharField(default=None, max_length=1000, null=True)),
                ("license_hash", models.CharField(default=None, max_length=1000, null=True)),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("version", models.CharField(max_length=1000)),
                ("required", models.BooleanField(default=False)),
                ("shared", models.BooleanField(default=False)),
                ("constraint", models.JSONField(default=functools.partial(list, *((0, "+"),)))),
                ("requires", models.JSONField(default=list)),
                ("bound_to", models.JSONField(default=dict)),
                ("adcm_min_version", models.CharField(default=None, max_length=1000, null=True)),
                (
                    "monitoring",
                    models.CharField(
                        choices=[("active", "active"), ("passive", "passive")], default="active", max_length=1000
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("config_group_customization", models.BooleanField(default=False)),
                ("venv", models.CharField(default="default", max_length=1000)),
                ("allow_maintenance_mode", models.BooleanField(default=False)),
                ("flag_autogeneration", models.JSONField(default=dict)),
                ("bundle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.bundle")),
                (
                    "parent",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.prototype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="host",
            name="prototype",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype"),
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("_multi_state", models.JSONField(db_column="multi_state", default=dict)),
                (
                    "_maintenance_mode",
                    models.CharField(
                        choices=[("on", "on"), ("off", "off"), ("changing", "changing")], default="off", max_length=1000
                    ),
                ),
                ("before_upgrade", models.JSONField(default=functools.partial(dict, *((("state", None),),)))),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="components", to="cm.cluster"
                    ),
                ),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, related_name="%(class)s_entities", to="cm.concernitem"),
                ),
                (
                    "config",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
                ),
                (
                    "prototype",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.prototype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cluster",
            name="prototype",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype"),
        ),
        migrations.CreateModel(
            name="ADCM",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("_multi_state", models.JSONField(db_column="multi_state", default=dict)),
                ("name", models.CharField(choices=[("ADCM", "ADCM")], max_length=1000, unique=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, related_name="%(class)s_entities", to="cm.concernitem"),
                ),
                (
                    "config",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
                ),
                ("prototype", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="action",
            name="prototype",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype"),
        ),
        migrations.CreateModel(
            name="PrototypeConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("subname", models.CharField(blank=True, max_length=1000)),
                ("default", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "string"),
                            ("text", "text"),
                            ("password", "password"),
                            ("secrettext", "secrettext"),
                            ("json", "json"),
                            ("integer", "integer"),
                            ("float", "float"),
                            ("option", "option"),
                            ("variant", "variant"),
                            ("boolean", "boolean"),
                            ("file", "file"),
                            ("secretfile", "secretfile"),
                            ("list", "list"),
                            ("map", "map"),
                            ("secretmap", "secretmap"),
                            ("structure", "structure"),
                            ("group", "group"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("limits", models.JSONField(default=dict)),
                ("ui_options", models.JSONField(blank=True, default=dict)),
                ("required", models.BooleanField(default=True)),
                ("group_customization", models.BooleanField(null=True)),
                ("ansible_options", models.JSONField(default=functools.partial(dict, *((("unsafe", False),),)))),
                (
                    "action",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.action"
                    ),
                ),
                ("prototype", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PrototypeExport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("prototype", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype")),
            ],
        ),
        migrations.CreateModel(
            name="PrototypeImport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("min_version", models.CharField(max_length=1000)),
                ("max_version", models.CharField(max_length=1000)),
                ("min_strict", models.BooleanField(default=False)),
                ("max_strict", models.BooleanField(default=False)),
                ("default", models.JSONField(default=None, null=True)),
                ("required", models.BooleanField(default=False)),
                ("multibind", models.BooleanField(default=False)),
                ("prototype", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype")),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("_multi_state", models.JSONField(db_column="multi_state", default=dict)),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("description", models.TextField(blank=True)),
                ("before_upgrade", models.JSONField(default=functools.partial(dict, *((("state", None),),)))),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, related_name="%(class)s_entities", to="cm.concernitem"),
                ),
                (
                    "config",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
                ),
                ("prototype", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="host",
            name="provider",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.provider"
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("_multi_state", models.JSONField(db_column="multi_state", default=dict)),
                (
                    "_maintenance_mode",
                    models.CharField(
                        choices=[("on", "on"), ("off", "off"), ("changing", "changing")], default="off", max_length=1000
                    ),
                ),
                ("before_upgrade", models.JSONField(default=functools.partial(dict, *((("state", None),),)))),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="services", to="cm.cluster"
                    ),
                ),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, related_name="%(class)s_entities", to="cm.concernitem"),
                ),
                (
                    "config",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.objectconfig"),
                ),
                ("prototype", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.prototype")),
            ],
        ),
        migrations.CreateModel(
            name="HostComponent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="created", max_length=1000)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.cluster")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.component")),
                ("host", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.host")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.service")),
            ],
        ),
        migrations.AddField(
            model_name="component",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="components", to="cm.service"
            ),
        ),
        migrations.CreateModel(
            name="ClusterBind",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.cluster")),
                (
                    "source_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="source_cluster", to="cm.cluster"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.service"
                    ),
                ),
                (
                    "source_service",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_service",
                        to="cm.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("script", models.CharField(max_length=1000)),
                (
                    "script_type",
                    models.CharField(
                        choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")],
                        max_length=1000,
                    ),
                ),
                ("state_on_fail", models.CharField(blank=True, max_length=1000)),
                ("multi_state_on_fail_set", models.JSONField(default=list)),
                ("multi_state_on_fail_unset", models.JSONField(default=list)),
                ("params", models.JSONField(default=dict)),
                ("allow_to_terminate", models.BooleanField(default=False)),
                ("action", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.action")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("owner_id", models.PositiveIntegerField(default=0)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("adcm", "adcm"),
                            ("cluster", "cluster"),
                            ("service", "service"),
                            ("component", "component"),
                            ("provider", "provider"),
                            ("host", "host"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("pid", models.PositiveIntegerField(blank=True, default=0)),
                ("selector", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("revoked", "revoked"),
                            ("created", "created"),
                            ("scheduled", "scheduled"),
                            ("queued", "queued"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("running", "running"),
                            ("locked", "locked"),
                            ("aborted", "aborted"),
                            ("broken", "broken"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("config", models.JSONField(default=None, null=True)),
                ("attr", models.JSONField(default=dict)),
                ("hostcomponentmap", models.JSONField(default=None, null=True)),
                ("post_upgrade_hc_map", models.JSONField(default=None, null=True)),
                ("hosts", models.JSONField(default=None, null=True)),
                ("verbose", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField(default=None, null=True)),
                ("finish_date", models.DateTimeField(default=None, null=True)),
                ("executor", models.JSONField(default=dict)),
                ("is_blocking", models.BooleanField(default=True)),
                ("process", models.JSONField(default=None, null=True)),
                ("name", models.CharField(default="-", max_length=1200)),
                ("display_name", models.CharField(default="-", max_length=1200)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.action"
                    ),
                ),
                (
                    "lock",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.concernitem"
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessStepInput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("configuration", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mapping", models.JSONField(default=dict, null=True)),
                ("step", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cm.processstep")),
                ("job", models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.tasklog")),
            ],
        ),
        migrations.AddField(
            model_name="joblog",
            name="task",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.tasklog"
            ),
        ),
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=1000)),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("min_version", models.CharField(max_length=1000)),
                ("max_version", models.CharField(max_length=1000)),
                ("from_edition", models.JSONField(default=functools.partial(list, *(("community",),)))),
                ("min_strict", models.BooleanField(default=False)),
                ("max_strict", models.BooleanField(default=False)),
                ("state_available", models.JSONField(default=list)),
                ("state_on_success", models.CharField(blank=True, max_length=1000)),
                (
                    "action",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.action"),
                ),
                ("bundle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.bundle")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnsibleConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.JSONField(default=dict)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("object_id", "object_type"), name="unique_ansibleconfig")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="concernitem",
            constraint=models.UniqueConstraint(
                fields=("name", "owner_id", "owner_type", "type"), name="cm_concernitem_name_owner_uc"
            ),
        ),
        migrations.AddConstraint(
            model_name="configrevision",
            constraint=models.UniqueConstraint(fields=("configlog",), name="unique_configlog"),
        ),
        migrations.AlterUniqueTogether(
            name="actionhostgroup",
            unique_together={("object_id", "object_type", "name")},
        ),
        migrations.AddIndex(
            model_name="hostinfo",
            index=models.Index(fields=["host"], name="cm_hostinfo_host_id_65bc27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="hostinfo",
            unique_together={("host",)},
        ),
        migrations.AddConstraint(
            model_name="groupchecklog",
            constraint=models.UniqueConstraint(fields=("job", "title"), name="unique_group_job"),
        ),
        migrations.AddConstraint(
            model_name="logstorage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "check")), fields=("job",), name="unique_check_job"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="confighostgroup",
            unique_together={("object_id", "name", "object_type")},
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(django.db.models.functions.text.Lower("name"), name="bundle_lower_name_idx"),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(django.db.models.functions.text.Lower("version"), name="bundle_lower_version_idx"),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(django.db.models.functions.text.Lower("edition"), name="bundle_lower_edition_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bundle",
            unique_together={("name", "version", "edition")},
        ),
        migrations.AlterUniqueTogether(
            name="prototype",
            unique_together={("bundle", "type", "parent", "name", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("prototype", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="prototypeconfig",
            unique_together={("prototype", "action", "name", "subname")},
        ),
        migrations.AlterUniqueTogether(
            name="prototypeexport",
            unique_together={("prototype", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="prototypeimport",
            unique_together={("prototype", "name")},
        ),
        migrations.AddConstraint(
            model_name="host",
            constraint=models.UniqueConstraint(
                condition=models.Q(("original", None)), fields=("fqdn",), name="unique_host_fqdn_with_original"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("cluster", "prototype")},
        ),
        migrations.AlterUniqueTogether(
            name="hostcomponent",
            unique_together={("host", "service", "component")},
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("cluster", "service", "prototype")},
        ),
        migrations.AlterUniqueTogether(
            name="clusterbind",
            unique_together={("cluster", "service", "source_cluster", "source_service")},
        ),
    ]
