# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.0.5 on 2018-09-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_auto_20180829_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterBind',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                (
                    'cluster',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Cluster'),
                ),
                (
                    'service',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='cm.Prototype',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='source',
                        to='cm.Cluster',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PrototypeExport',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('name', models.CharField(max_length=160)),
                (
                    'prototype',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Prototype'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PrototypeImport',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('name', models.CharField(max_length=160)),
                ('min_version', models.CharField(max_length=80)),
                ('max_version', models.CharField(max_length=80)),
                (
                    'prototype',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Prototype'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='StagePrototypeExport',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('name', models.CharField(max_length=160)),
                (
                    'prototype',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.StagePrototype'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='StagePrototypeImport',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('name', models.CharField(max_length=160)),
                ('min_version', models.CharField(max_length=80)),
                ('max_version', models.CharField(max_length=80)),
                (
                    'prototype',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.StagePrototype'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stageprototypeimport',
            unique_together={('prototype', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stageprototypeexport',
            unique_together={('prototype', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='prototypeimport',
            unique_together={('prototype', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='prototypeexport',
            unique_together={('prototype', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='clusterbind',
            unique_together={('cluster', 'source', 'service')},
        ),
    ]
