# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.0.5 on 2018-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cm', '0006_auto_20181009_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='stack',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clusterobject',
            name='stack',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='host',
            name='stack',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joblog',
            name='pid',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='pid',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
