# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.0.5 on 2018-12-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0011_auto_20181220_1327"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceComponent",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "cluster",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.Cluster"),
                ),
                (
                    "component",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.Component"),
                ),
                (
                    "service",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.ClusterObject"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hostcomponent",
            name="component",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.ServiceComponent"),
        ),
        migrations.AlterField(
            model_name="hostcomponent",
            name="service",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.ClusterObject"),
        ),
        migrations.AlterUniqueTogether(
            name="servicecomponent",
            unique_together={("cluster", "service", "component")},
        ),
    ]
