# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.0.5 on 2019-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cm', '0014_auto_20190124_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='action',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='component',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='prototype',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='stageaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stageaction',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='stagecomponent',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='stageprototype',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
