# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.0.5 on 2019-02-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0015_auto_20190128_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prototype',
            unique_together={('bundle', 'type', 'name', 'version')},
        ),
    ]
