# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 2.1.7 on 2019-06-07 10:27
# pylint: disable=line-too-long

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0020_auto_20190321_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterbind', old_name='source', new_name='source_cluster'
        ),
        migrations.RenameField(
            model_name='clusterbind', old_name='service', new_name='source_service'
        ),
        migrations.AddField(
            model_name='clusterbind',
            name='service',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='cm.ClusterObject',
            ),
        ),
        migrations.AlterField(
            model_name='prototypeconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('text', 'text'),
                    ('password', 'password'),
                    ('json', 'json'),
                    ('integer', 'integer'),
                    ('float', 'float'),
                    ('option', 'option'),
                    ('boolean', 'boolean'),
                    ('file', 'file'),
                    ('list', 'list'),
                    ('map', 'map'),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='stageprototypeconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('text', 'text'),
                    ('password', 'password'),
                    ('json', 'json'),
                    ('integer', 'integer'),
                    ('float', 'float'),
                    ('option', 'option'),
                    ('boolean', 'boolean'),
                    ('file', 'file'),
                    ('list', 'list'),
                    ('map', 'map'),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='clusterbind',
            unique_together={('cluster', 'service', 'source_cluster', 'source_service')},
        ),
    ]
