# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 2.2.4 on 2019-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0033_auto_20191023_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='button',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stageaction',
            name='button',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
