# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.0.7 on 2020-07-14 07:41

from django.db import migrations, models


# Operations for prototypeconfig and stageprototypeconfig models refer
# to commit 3b30a2691bc301bf8afd2c305bea6b40824afc54
class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0055_auto_20200424_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prototypeconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("string", "string"),
                    ("text", "text"),
                    ("password", "password"),
                    ("json", "json"),
                    ("integer", "integer"),
                    ("float", "float"),
                    ("option", "option"),
                    ("variant", "variant"),
                    ("boolean", "boolean"),
                    ("file", "file"),
                    ("list", "list"),
                    ("map", "map"),
                    ("structure", "structure"),
                    ("group", "group"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stageprototypeconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("string", "string"),
                    ("text", "text"),
                    ("password", "password"),
                    ("json", "json"),
                    ("integer", "integer"),
                    ("float", "float"),
                    ("option", "option"),
                    ("variant", "variant"),
                    ("boolean", "boolean"),
                    ("file", "file"),
                    ("list", "list"),
                    ("map", "map"),
                    ("structure", "structure"),
                    ("group", "group"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="groupchecklog",
            constraint=models.UniqueConstraint(fields=("job_id", "title"), name="unique_group_job"),
        ),
    ]
