# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by Django 3.0.5 on 2020-09-07 15:30

import cm.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0057_auto_20200831_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='binded_to',
            field=cm.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='stagecomponent',
            name='binded_to',
            field=cm.models.JSONField(default={}),
        ),
    ]
