# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.1.2 on 2020-12-08 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0060_auto_20201201_1122"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="component",
            name="comp_prototype",
        ),
        migrations.RemoveField(
            model_name="component",
            name="prototype",
        ),
        migrations.AlterUniqueTogether(
            name="servicecomponent",
            unique_together={("cluster", "service", "prototype")},
        ),
        migrations.DeleteModel(
            name="StageComponent",
        ),
        migrations.RemoveField(
            model_name="servicecomponent",
            name="component",
        ),
        migrations.DeleteModel(
            name="Component",
        ),
    ]
