# Generated by Django 3.1.1 on 2021-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0063_tasklog_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypeconfig',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('text', 'text'), ('password', 'password'), ('secrettext', 'secrettext'), ('json', 'json'), ('integer', 'integer'), ('float', 'float'), ('option', 'option'), ('variant', 'variant'), ('boolean', 'boolean'), ('file', 'file'), ('list', 'list'), ('map', 'map'), ('structure', 'structure'), ('group', 'group')], max_length=16),
        ),
        migrations.AlterField(
            model_name='stageprototypeconfig',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('text', 'text'), ('password', 'password'), ('secrettext', 'secrettext'), ('json', 'json'), ('integer', 'integer'), ('float', 'float'), ('option', 'option'), ('variant', 'variant'), ('boolean', 'boolean'), ('file', 'file'), ('list', 'list'), ('map', 'map'), ('structure', 'structure'), ('group', 'group')], max_length=16),
        ),
    ]
