# Generated by Django 3.1.2 on 2021-04-27 08:53

from django.db import migrations, models
import django.db.models.deletion


def fix_tasklog(apps, schema_editor):
    TaskLog = apps.get_model('cm', 'TaskLog')
    Action = apps.get_model('cm', 'Action')
    for task in TaskLog.objects.all():
        if task.old_action_id:
            try:
                action = Action.objects.get(id=task.old_action_id)
                task.action = action
                task.save()
            except Action.DoesNotExist:
                pass

def fix_joblog(apps, schema_editor):
    JobLog = apps.get_model('cm', 'JobLog')
    TaskLog = apps.get_model('cm', 'TaskLog')
    Action = apps.get_model('cm', 'Action')
    SubAction = apps.get_model('cm', 'SubAction')
    for job in JobLog.objects.all():
        if job.old_action_id:
            try:
                action = Action.objects.get(id=job.old_action_id)
                job.action = action
            except Action.DoesNotExist:
                pass
        if job.old_sub_action_id:
            try:
                sub_action = SubAction.objects.get(id=job.old_sub_action_id)
                job.sub_action = sub_action
            except Action.DoesNotExist:
                pass
        try:
            task = TaskLog.objects.get(id=job.old_task_id)
            job.task = task
        except TaskLog.DoesNotExist:
            pass
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0065_auto_20210220_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblog',
            old_name='action_id',
            new_name='old_action_id',
        ),
        migrations.RenameField(
            model_name='joblog',
            old_name='sub_action_id',
            new_name='old_sub_action_id',
        ),
        migrations.RenameField(
            model_name='joblog',
            old_name='task_id',
            new_name='old_task_id',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='action_id',
            new_name='old_action_id',
        ),
        migrations.AddField(
            model_name='joblog',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.action'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='sub_action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.subaction'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.tasklog'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.action'),
        ),
        migrations.RunPython(fix_tasklog),
        migrations.RunPython(fix_joblog),
    ]
