# Generated by Django 3.2 on 2021-05-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0066_auto_20210427_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfigHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.objectconfig')),
                ('host', models.ManyToManyField(blank=True, to='cm.Host')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='cm.clusterobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderConfigHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.objectconfig')),
                ('host', models.ManyToManyField(blank=True, to='cm.Host')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='cm.hostprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentConfigHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.objectconfig')),
                ('host', models.ManyToManyField(blank=True, to='cm.Host')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='cm.servicecomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterConfigHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.objectconfig')),
                ('host', models.ManyToManyField(blank=True, to='cm.Host')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='cm.cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
