# Generated by Django 3.2.4 on 2021-08-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0067_tasklog_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.action'),
        ),
    ]
