# Generated by Django 3.1.2 on 2021-05-26 08:41
# pylint: disable=line-too-long

from django.db import migrations, models
import django.db.models.deletion


def fix_hc(apps, schema_editor):
    HostComponent = apps.get_model('cm', 'HostComponent')
    for hc in HostComponent.objects.all():
        hc.new_cluster = hc.old_cluster.super
        hc.new_host = hc.old_host.super
        hc.new_service = hc.old_service.super
        hc.new_component = hc.old_component.super
        hc.save()


def fix_bind(apps, schema_editor):
    ClusterBind = apps.get_model('cm', 'ClusterBind')
    for cb in ClusterBind.objects.all():
        cb.new_cluster = cb.old_cluster.super
        cb.new_service = cb.old_service.super
        cb.new_source_cluster = cb.old_source_cluster.super
        if cb.old_source_cluster:
            cb.new_source_service = cb.old_source_service.super
        cb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0067_auto_20210521_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterbind',
            old_name='cluster',
            new_name='old_cluster',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='service',
            new_name='old_service',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='source_cluster',
            new_name='old_source_cluster',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='source_service',
            new_name='old_source_service',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='cluster',
            new_name='old_cluster',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='component',
            new_name='old_component',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='host',
            new_name='old_host',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='service',
            new_name='old_service',
        ),
        migrations.AddField(
            model_name='clusterbind',
            name='new_cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bind_cluster', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='clusterbind',
            name='new_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bind_service', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='clusterbind',
            name='new_source_cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bind_source_cluster', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='clusterbind',
            name='new_source_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bind_source_service', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='hostcomponent',
            name='new_cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hc_cluster', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='hostcomponent',
            name='new_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hc_component', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='hostcomponent',
            name='new_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hc_host', to='cm.allobjects'),
        ),
        migrations.AddField(
            model_name='hostcomponent',
            name='new_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hc_service', to='cm.allobjects'),
        ),
        migrations.AlterUniqueTogether(
            name='allobjects',
            unique_together={('type', 'prototype', 'name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='clusterbind',
            unique_together={('old_cluster', 'old_service', 'old_source_cluster', 'old_source_service')},
        ),
        migrations.AlterUniqueTogether(
            name='hostcomponent',
            unique_together={('old_host', 'old_service', 'old_component')},
        ),
        migrations.RunPython(fix_hc),
        migrations.RunPython(fix_bind),
    ]
