# Generated by Django 3.2 on 2021-06-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0067_split_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default=None, max_length=160, null=True, unique=True)),
                ('reason', models.JSONField(default=dict)),
                ('blocking', models.BooleanField(default=True)),
                (
                    'source',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.joint'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='joint',
            name='agenda',
            field=models.ManyToManyField(blank=True, related_name='joints', to='cm.AgendaItem'),
        ),
    ]
