# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.4 on 2021-08-05 14:31

import django.db.models.deletion
from django.db import migrations, models


def fix_joblog(apps, schema_editor):
    JobLog = apps.get_model('cm', 'JobLog')
    LogStorage = apps.get_model('cm', 'LogStorage')
    LogStorage.objects.filter(job__task_id__isnull=True).delete()
    JobLog.objects.filter(task_id__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('cm', '0067_tasklog_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='action',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='cm.action',
            ),
        ),
        migrations.RunPython(fix_joblog),
    ]
