# Generated by Django 3.1.2 on 2021-05-26 09:02
# pylint: disable=line-too-long

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0068_auto_20210526_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='config',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='super',
        ),
        migrations.AlterUniqueTogether(
            name='clusterobject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clusterobject',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='clusterobject',
            name='config',
        ),
        migrations.RemoveField(
            model_name='clusterobject',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='clusterobject',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clusterobject',
            name='super',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='host',
            name='config',
        ),
        migrations.RemoveField(
            model_name='host',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='host',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='host',
            name='super',
        ),
        migrations.RemoveField(
            model_name='hostprovider',
            name='config',
        ),
        migrations.RemoveField(
            model_name='hostprovider',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='hostprovider',
            name='super',
        ),
        migrations.AlterUniqueTogether(
            name='servicecomponent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicecomponent',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='servicecomponent',
            name='config',
        ),
        migrations.RemoveField(
            model_name='servicecomponent',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='servicecomponent',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicecomponent',
            name='super',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='new_cluster',
            new_name='cluster',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='new_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='new_source_cluster',
            new_name='source_cluster',
        ),
        migrations.RenameField(
            model_name='clusterbind',
            old_name='new_source_service',
            new_name='source_service',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='new_cluster',
            new_name='cluster',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='new_component',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='new_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='hostcomponent',
            old_name='new_service',
            new_name='service',
        ),
        migrations.AlterUniqueTogether(
            name='clusterbind',
            unique_together={('cluster', 'service', 'source_cluster', 'source_service')},
        ),
        migrations.AlterUniqueTogether(
            name='hostcomponent',
            unique_together={('host', 'service', 'component')},
        ),
        migrations.DeleteModel(
            name='ADCM',
        ),
        migrations.DeleteModel(
            name='HostProvider',
        ),
        migrations.RemoveField(
            model_name='clusterbind',
            name='old_cluster',
        ),
        migrations.RemoveField(
            model_name='clusterbind',
            name='old_service',
        ),
        migrations.RemoveField(
            model_name='clusterbind',
            name='old_source_cluster',
        ),
        migrations.RemoveField(
            model_name='clusterbind',
            name='old_source_service',
        ),
        migrations.RemoveField(
            model_name='hostcomponent',
            name='old_cluster',
        ),
        migrations.RemoveField(
            model_name='hostcomponent',
            name='old_component',
        ),
        migrations.RemoveField(
            model_name='hostcomponent',
            name='old_host',
        ),
        migrations.RemoveField(
            model_name='hostcomponent',
            name='old_service',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='ClusterObject',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='ServiceComponent',
        ),
        migrations.CreateModel(
            name='ADCM',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cm.allobjects',),
        ),
        migrations.CreateModel(
            name='HostProvider',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cm.allobjects',),
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cm.allobjects',),
        ),
        migrations.CreateModel(
            name='ClusterObject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cm.allobjects',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cm.allobjects',),
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cm.allobjects',),
        ),
    ]
