# Generated by Django 3.2.6 on 2021-09-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0069_auto_20210607_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='config_group_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stageprototype',
            name='config_group_customized',
            field=models.BooleanField(default=False),
        ),
    ]
