# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2 on 2021-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0074_auto_20210903_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="multi_state_available",
            field=models.JSONField(default="any"),
        ),
        migrations.AddField(
            model_name="action",
            name="multi_state_on_fail_set",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="action",
            name="multi_state_on_fail_unset",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="action",
            name="multi_state_on_success_set",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="action",
            name="multi_state_on_success_unset",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="action",
            name="multi_state_unavailable",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="action",
            name="state_unavailable",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="multi_state_available",
            field=models.JSONField(default="any"),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="multi_state_on_fail_set",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="multi_state_on_fail_unset",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="multi_state_on_success_set",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="multi_state_on_success_unset",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="multi_state_unavailable",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="state_unavailable",
            field=models.JSONField(default=list),
        ),
    ]
