# Generated by Django 3.2 on 2021-10-13 12:50

import cm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0075_actions_multistate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='multi_state_available',
            field=models.JSONField(default=cm.models.get_any),
        ),
        migrations.AlterField(
            model_name='stageaction',
            name='multi_state_available',
            field=models.JSONField(default=cm.models.get_any),
        ),
    ]
