# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 3.2 on 2021-10-13 12:50

from django.db import migrations, models

import cm.models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0075_actions_multistate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='multi_state_available',
            field=models.JSONField(default=cm.models.get_any),
        ),
        migrations.AlterField(
            model_name='stageaction',
            name='multi_state_available',
            field=models.JSONField(default=cm.models.get_any),
        ),
    ]
