# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2 on 2021-10-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cm", "0078_alter_groupconfig_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="concernitem",
            name="cause",
            field=models.CharField(
                choices=[
                    ("config", "config"),
                    ("job", "job"),
                    ("host-component", "host-component"),
                    ("import", "import"),
                    ("service", "service"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="concernitem",
            name="owner_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="concernitem",
            name="owner_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
