# Generated by Django 3.2 on 2021-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0079_concernitem_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagesubaction',
            name='multi_state_on_fail_set',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='stagesubaction',
            name='multi_state_on_fail_unset',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='subaction',
            name='multi_state_on_fail_set',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='subaction',
            name='multi_state_on_fail_unset',
            field=models.JSONField(default=list),
        ),
    ]
