# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.9 on 2022-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0080_subaction_multi_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='state_before_upgrade',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hostprovider',
            name='state_before_upgrade',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
