# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.7 on 2021-09-29 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0081_auto_20220114_1246"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="group",
        ),
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="role",
            name="user",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
