# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2 on 2021-12-16 13:57

import django.db.models.deletion
from django.db import migrations, models


def fill_category(apps, schema_editor):
    """Add category records and link them to bundles"""
    Bundle = apps.get_model('cm', 'Bundle')
    ProductCategory = apps.get_model('cm', 'ProductCategory')
    Prototype = apps.get_model('cm', 'Prototype')
    for bundle in Bundle.objects.all():
        prototype = Prototype.objects.filter(
            bundle=bundle, name=bundle.name, type='cluster'
        ).first()
        if prototype:  # skip non-product bundles
            value = prototype.display_name or bundle.name
            category, _ = ProductCategory.objects.get_or_create(value=value)
            bundle.category = category
            bundle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0082_remove_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('value', models.CharField(max_length=160, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='category',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to='cm.productcategory'
            ),
        ),
        migrations.RunPython(fill_category),
    ]
