# Generated by Django 3.2.4 on 2022-03-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0084_ansible_venv'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageupgrade',
            name='action',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.stageaction'
            ),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='action',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.action'
            ),
        ),
    ]
