# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.4 on 2022-03-31 10:20

from django.db import migrations


def update_adcm_config_settings(apps, schema_editor):
    ADCM = apps.get_model('cm', 'ADCM')
    ConfigLog = apps.get_model('cm', 'ConfigLog')
    for adcm in ADCM.objects.all():
        cl = ConfigLog.objects.get(id=adcm.config.current)
        config = cl.config
        if 'ansible_settings' in config and 'mitogen' in config['ansible_settings']:
            config['ansible_settings']['mitogen'] = False
            obj_conf = adcm.config
            config_log = ConfigLog(obj_ref=obj_conf, config=config, attr=cl.attr, description=cl.description)
            config_log.save()
            obj_conf.previous = obj_conf.current
            obj_conf.current = config_log.id
            obj_conf.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cm', '0085_add_action_to_upgrade'),
    ]

    operations = [
        migrations.RunPython(update_adcm_config_settings),
    ]
