# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.4 on 2022-03-31 10:20

from django.db import migrations
from cm.api import update_obj_config


def update_adcm_config_settings(apps, schema_editor):
    ADCM = apps.get_model('cm', 'ADCM')
    ConfigLog = apps.get_model('cm', 'ConfigLog')
    adcm = ADCM.objects.get(id=1)
    config_log = ConfigLog.objects.get(id=adcm.config.id)
    config = config_log.config
    config['ansible_settings']['mitogen'] = False
    update_obj_config(adcm.config, config, config_log.attr, config_log.description)


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0085_add_action_to_upgrade'),
    ]

    operations = [
        migrations.RunPython(update_adcm_config_settings),
    ]
