# Generated by Django 3.2.13 on 2022-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0086_set_mitogen_to_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='maintenance_mode',
            field=models.CharField(
                choices=[('disabled', 'disabled'), ('on', 'on'), ('off', 'off')],
                default='disabled',
                max_length=16,
            ),
        ),
    ]
