# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.13 on 2022-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0086_set_mitogen_to_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="maintenance_mode",
            field=models.CharField(
                choices=[("disabled", "disabled"), ("on", "on"), ("off", "off")],
                default="disabled",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="allow_in_maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prototype",
            name="allow_maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="allow_in_maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stageprototype",
            name="allow_maintenance_mode",
            field=models.BooleanField(default=False),
        ),
    ]
