# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.1.2 on 2022-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cm', '0088_fix_group_keys_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='post_upgrade_hc_map',
            field=models.JSONField(default=None, null=True),
        ),
    ]
