# Generated by Django 3.2.13 on 2022-05-31 11:09

from django.db import migrations


def __rm_tables_id_exists():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0088_fix_group_keys_structure'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS main.background_task;
            DROP TABLE IF EXISTS main.background_task_completedtask;
            """
        ),
    ]
