# Generated by Django 3.2.15 on 2022-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0092_auto_20220906_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='host',
            name='fqdn',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='stageaction',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='stageprototype',
            name='display_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
