# Generated by Django 3.2.13 on 2022-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0092_auto_20220906_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
