# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.13 on 2022-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cm", "0094_increase_of_maxlength_to_postgress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prototype",
            name="display_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="prototypeconfig",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="prototypeconfig",
            name="subname",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="prototypeconfig",
            name="display_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="stageprototype",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="stageprototypeconfig",
            name="display_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="stageprototypeconfig",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="stageprototypeconfig",
            name="subname",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='stagesubaction',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subaction',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
