# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# noqa: N999

# Generated by Django 3.2.15 on 2022-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0094_increase_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblog",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("running", "running"),
                    ("locked", "locked"),
                    ("aborted", "aborted"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("running", "running"),
                    ("locked", "locked"),
                    ("aborted", "aborted"),
                ],
                max_length=16,
            ),
        ),
    ]
