# Generated by Django 3.2.15 on 2022-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0094_increase_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
