# Generated by Django 3.2.15 on 2022-11-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0095_JobStatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='button',
        ),
        migrations.RemoveField(
            model_name='stageaction',
            name='button',
        ),
        migrations.AddField(
            model_name='clusterobject',
            name='_maintenance_mode',
            field=models.CharField(
                choices=[('ON', 'ON'), ('OFF', 'OFF'), ('CHANGING', 'CHANGING')],
                default='OFF',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='servicecomponent',
            name='_maintenance_mode',
            field=models.CharField(
                choices=[('ON', 'ON'), ('OFF', 'OFF'), ('CHANGING', 'CHANGING')],
                default='OFF',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='host',
            name='maintenance_mode',
            field=models.CharField(
                choices=[('ON', 'ON'), ('OFF', 'OFF'), ('CHANGING', 'CHANGING')],
                default='OFF',
                max_length=64,
            ),
        ),
    ]
