# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.15 on 2022-11-01 10:10

from django.db import migrations, models


def migrate_host_maintenance_mode(apps, schema_editor):
    host_model = apps.get_model("cm", "Host")

    host_model.objects.filter(maintenance_mode="on").update(maintenance_mode="ON")
    host_model.objects.filter(models.Q(maintenance_mode="off") | models.Q(maintenance_mode="disabled")).update(
        maintenance_mode="OFF"
    )


def migrate_host_maintenance_mode_reverse(apps, schema_editor):
    host_model = apps.get_model("cm", "Host")

    host_model.objects.filter(
        models.Q(cluster__isnull=True) | models.Q(cluster__prototype__allow_maintenance_mode=False)
    ).update(maintenance_mode="disabled")

    host_model.objects.filter(maintenance_mode="ON").update(maintenance_mode="on")
    host_model.objects.filter(maintenance_mode="OFF").update(maintenance_mode="off")


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0095_JobStatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="button",
        ),
        migrations.RemoveField(
            model_name="stageaction",
            name="button",
        ),
        migrations.AddField(
            model_name="clusterobject",
            name="_maintenance_mode",
            field=models.CharField(
                choices=[("ON", "ON"), ("OFF", "OFF"), ("CHANGING", "CHANGING")],
                default="OFF",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="servicecomponent",
            name="_maintenance_mode",
            field=models.CharField(
                choices=[("ON", "ON"), ("OFF", "OFF"), ("CHANGING", "CHANGING")],
                default="OFF",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="maintenance_mode",
            field=models.CharField(
                choices=[("ON", "ON"), ("OFF", "OFF"), ("CHANGING", "CHANGING")],
                default="OFF",
                max_length=64,
            ),
        ),
        migrations.RunPython(code=migrate_host_maintenance_mode, reverse_code=migrate_host_maintenance_mode_reverse),
    ]
