# Generated by Django 3.2.15 on 2022-10-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0095_alter_host_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterobject',
            name='_maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecomponent',
            name='_maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
