# Generated by Django 3.2.15 on 2022-10-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0096_auto_20221007_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='button',
        ),
        migrations.RemoveField(
            model_name='stageaction',
            name='button',
        ),
    ]
