# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.15 on 2022-11-09 12:38

from django.db import migrations, models


def migrate_bundle_license(apps, schema_editor):
    bundle_model = apps.get_model("cm", "Bundle")
    proto_model = apps.get_model("cm", "Prototype")
    bundles = bundle_model.objects.filter(license__in=["accepted", "unaccepted"])
    for bundle in bundles:
        proto_model.objects.filter(bundle=bundle, name=bundle.name).update(
            license=bundle.license, license_hash=bundle.license_hash, license_path=bundle.license_path
        )


def migrate_bundle_license_reverse(apps, schema_editor):
    proto_model = apps.get_model("cm", "Prototype")

    prototypes = proto_model.objects.filter(license__in=["accepted", "unaccepted"], type__in=["cluster", "provider"])
    for proto in prototypes:
        proto.bundle.update(license=proto.license, license_hash=proto.license_hash, license_path=proto.license_path)


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0096_auto_20221101_1010"),
    ]

    operations = [
        migrations.AddField(
            model_name="prototype",
            name="license",
            field=models.CharField(
                choices=[("absent", "absent"), ("accepted", "accepted"), ("unaccepted", "unaccepted")],
                default="absent",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="prototype",
            name="license_hash",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="prototype",
            name="license_path",
            field=models.CharField(default=None, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="stageprototype",
            name="license",
            field=models.CharField(
                choices=[("absent", "absent"), ("accepted", "accepted"), ("unaccepted", "unaccepted")],
                default="absent",
                max_length=16,
            ),
        ),
        migrations.RunPython(code=migrate_bundle_license, reverse_code=migrate_bundle_license_reverse),
        migrations.RemoveField(
            model_name="bundle",
            name="license",
        ),
        migrations.RemoveField(
            model_name="bundle",
            name="license_hash",
        ),
        migrations.RemoveField(
            model_name="bundle",
            name="license_path",
        ),
    ]
