# Generated by Django 3.2.15 on 2022-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0097_auto_20221017_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterobject',
            name='_maintenance_mode',
            field=models.CharField(
                choices=[('ON', 'ON'), ('OFF', 'OFF'), ('CHANGING', 'CHANGING')],
                default='OFF',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='host',
            name='maintenance_mode',
            field=models.CharField(
                choices=[('ON', 'ON'), ('OFF', 'OFF'), ('CHANGING', 'CHANGING')],
                default='OFF',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='servicecomponent',
            name='_maintenance_mode',
            field=models.CharField(
                choices=[('ON', 'ON'), ('OFF', 'OFF'), ('CHANGING', 'CHANGING')],
                default='OFF',
                max_length=64,
            ),
        ),
    ]
