# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.15 on 2022-11-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cm', '0097_auto_20221109_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypeconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('text', 'text'),
                    ('password', 'password'),
                    ('secrettext', 'secrettext'),
                    ('json', 'json'),
                    ('integer', 'integer'),
                    ('float', 'float'),
                    ('option', 'option'),
                    ('variant', 'variant'),
                    ('boolean', 'boolean'),
                    ('file', 'file'),
                    ('secretfile', 'secretfile'),
                    ('list', 'list'),
                    ('map', 'map'),
                    ('secretmap', 'secretmap'),
                    ('structure', 'structure'),
                    ('group', 'group'),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='stageprototypeconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('text', 'text'),
                    ('password', 'password'),
                    ('secrettext', 'secrettext'),
                    ('json', 'json'),
                    ('integer', 'integer'),
                    ('float', 'float'),
                    ('option', 'option'),
                    ('variant', 'variant'),
                    ('boolean', 'boolean'),
                    ('file', 'file'),
                    ('secretfile', 'secretfile'),
                    ('list', 'list'),
                    ('map', 'map'),
                    ('secretmap', 'secretmap'),
                    ('structure', 'structure'),
                    ('group', 'group'),
                ],
                max_length=16,
            ),
        ),
    ]
