# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.3 on 2022-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0098_auto_20221115_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyData',
        ),
        migrations.AlterField(
            model_name='adcm',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='clusterobject',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='host',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='hostprovider',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='servicecomponent',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
    ]
