# Generated by Django 4.1.3 on 2022-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0098_auto_20221115_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyData',
        ),
        migrations.AlterField(
            model_name='adcm',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='clusterobject',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='host',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='hostprovider',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
        migrations.AlterField(
            model_name='servicecomponent',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_entities', to='cm.concernitem'),
        ),
    ]
