# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 4.1.3 on 2022-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0099_alter_adcm_concerns_alter_cluster_concerns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagesubaction',
            name='allow_to_terminate',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subaction',
            name='allow_to_terminate',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
