# Generated by Django 4.1.3 on 2022-12-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0100_subaction_allow_terminate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyData',
        ),
    ]
