# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.17 on 2023-02-13 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0103_auto_20230131_0946"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joblog",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="prototypeconfig",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="stageprototypeconfig",
            options={"ordering": ["id"]},
        ),
    ]
