# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Generated by Django 3.2.18 on 2023-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0106_set_nginx_rotate_config_to_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageupgrade",
            name="display_name",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="upgrade",
            name="display_name",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
