# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2 on 2021-07-22 07:18

from django.db import migrations, models

data = [
    {
        "name": "unsatisfied service requirement",
        "template": {
            "message": "${source} has an issue with requirement. Need to be installed: ${target}",
            "placeholder": {
                "source": {"type": "adcm_entity"},
                "target": {"type": "prototype"},
            },
        },
    },
]


def insert_message_templates(apps, schema_editor):
    message_template = apps.get_model("cm", "MessageTemplate")
    message_template.objects.bulk_create([message_template(**kwargs) for kwargs in data])


def insert_message_templates_revert(apps, schema_editor):
    message_template = apps.get_model("cm", "MessageTemplate")
    message_template.objects.filter(name="unsatisfied service requirement").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0107_set_nginx_rotate_config_to_defaults"),
    ]
    operations = [
        migrations.AlterField(
            model_name="concernitem",
            name="cause",
            field=models.CharField(
                choices=[
                    ("config", "config"),
                    ("job", "job"),
                    ("host-component", "host-component"),
                    ("import", "import"),
                    ("service", "service"),
                    ("requirement", "requirement"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.RunPython(code=insert_message_templates, reverse_code=insert_message_templates_revert),
    ]
