# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2 on 2021-07-22 07:18

from django.db import migrations

data = {
    "name": "required service issue",
    "template": {
        "message": "${source} require service ${target} to be installed",
        "placeholder": {
            "source": {"type": "adcm_entity"},
            "target": {"type": "prototype"},
        },
    },
}

reversed_data = [
    {
        "name": "required service issue",
        "template": {
            "message": "${source} has an issue with required service.",
            "placeholder": {
                "source": {"type": "adcm_entity"},
            },
        },
    },
]


def insert_message_templates(apps, schema_editor):
    message_template = apps.get_model("cm", "MessageTemplate")
    required_msg = message_template.objects.get(name="required service issue")
    required_msg.template["message"] = data["template"]["message"]
    required_msg.template["placeholder"] = data["template"]["placeholder"]
    required_msg.save()


def insert_message_templates_revert(apps, schema_editor):
    message_template = apps.get_model("cm", "MessageTemplate")
    message_template.objects.filter(name="required service issue").delete()
    message_template.objects.bulk_create([message_template(**kwargs) for kwargs in reversed_data])


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0109_message_template_requires_service"),
    ]
    operations = [
        migrations.RunPython(code=insert_message_templates, reverse_code=insert_message_templates_revert),
    ]
