# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.19 on 2023-08-07 08:56

from django.db import migrations, models

TRANSLATIONS = {"ON": "on", "OFF": "off", "CHANGING": "changing"}


def mm_to_lowercase(apps, schema_editor):
    Host = apps.get_model("cm", "Host")
    ClusterObject = apps.get_model("cm", "ClusterObject")
    ServiceComponent = apps.get_model("cm", "ServiceComponent")

    for old_value, new_value in TRANSLATIONS.items():
        Host.objects.filter(maintenance_mode=old_value).update(maintenance_mode=new_value)
        ClusterObject.objects.filter(_maintenance_mode=old_value).update(_maintenance_mode=new_value)
        ServiceComponent.objects.filter(_maintenance_mode=old_value).update(_maintenance_mode=new_value)


def mm_to_uppercase(apps, schema_editor):
    Host = apps.get_model("cm", "Host")
    ClusterObject = apps.get_model("cm", "ClusterObject")
    ServiceComponent = apps.get_model("cm", "ServiceComponent")

    for new_value, old_value in TRANSLATIONS.items():
        Host.objects.filter(maintenance_mode=old_value).update(maintenance_mode=new_value)
        ClusterObject.objects.filter(_maintenance_mode=old_value).update(_maintenance_mode=new_value)
        ServiceComponent.objects.filter(_maintenance_mode=old_value).update(_maintenance_mode=new_value)


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0112_bundle_signature_status"),
    ]

    operations = [
        migrations.RunPython(code=mm_to_lowercase, reverse_code=mm_to_uppercase),
        migrations.AlterField(
            model_name="clusterobject",
            name="_maintenance_mode",
            field=models.CharField(
                choices=[("on", "on"), ("off", "off"), ("changing", "changing")], default="off", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="maintenance_mode",
            field=models.CharField(
                choices=[("on", "on"), ("off", "off"), ("changing", "changing")], default="off", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="servicecomponent",
            name="_maintenance_mode",
            field=models.CharField(
                choices=[("on", "on"), ("off", "off"), ("changing", "changing")], default="off", max_length=1000
            ),
        ),
    ]
