# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-04-09 11:31

from django.db import migrations
from django.db.models import Q


def fix_null_jsonfield(apps, schema_editor):
    Action = apps.get_model("cm", "Action")
    Action.objects.filter(Q(ui_options__isnull=True) | Q(ui_options="{}")).update(ui_options={})


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0059_auto_20200904_0910"),
        ("cm", "0115_auto_20231025_1823"),
    ]

    operations = [
        migrations.RunPython(code=fix_null_jsonfield, reverse_code=migrations.RunPython.noop),
    ]
