# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-02-22 10:06
from operator import itemgetter

from django.db import migrations, models


def extract_sub_action_data_to_joblogs(apps, schema_editor):
    JobLog = apps.get_model("cm", "JobLog")
    SubAction = apps.get_model("cm", "SubAction")
    Action = apps.get_model("cm", "Action")

    for action in Action.objects.filter(type="task"):
        SubAction.objects.filter(action=action, allow_to_terminate__isnull=True).update(
            allow_to_terminate=action.allow_to_terminate
        )

    requested_for_update = JobLog.objects.values("id", "sub_action_id").filter(sub_action__isnull=False)
    fields_to_move = (
        "name",
        "display_name",
        "allow_to_terminate",
        "script",
        "script_type",
        "state_on_fail",
        "multi_state_on_fail_set",
        "multi_state_on_fail_unset",
        "params",
    )
    for sub_action_update_dict in SubAction.objects.values("id", *fields_to_move).filter(
        id__in=set(map(itemgetter("sub_action_id"), requested_for_update))
    ):
        sub_action_id = sub_action_update_dict.pop("id")
        JobLog.objects.filter(sub_action_id=sub_action_id).update(**sub_action_update_dict)

    default_to_fill = {"name": "unknown", "script": "unknown", "script_type": "ansible"}
    JobLog.objects.filter(sub_action__isnull=True).update(**default_to_fill)


def do_nothing(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0116_fix_null_jsonfield"),
    ]

    operations = [
        # create nullable fields
        migrations.AlterField(
            model_name="joblog",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("running", "running"),
                    ("locked", "locked"),
                    ("aborted", "aborted"),
                    ("broken", "broken"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("running", "running"),
                    ("locked", "locked"),
                    ("aborted", "aborted"),
                    ("broken", "broken"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="multi_state_on_fail_set",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="joblog",
            name="multi_state_on_fail_unset",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="joblog",
            name="params",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="joblog",
            name="script",
            field=models.CharField(max_length=1000, default="unknown"),
        ),
        migrations.AddField(
            model_name="joblog",
            name="script_type",
            field=models.CharField(
                choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")],
                max_length=1000,
                default="ansible",
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="state_on_fail",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="joblog",
            name="allow_to_terminate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="joblog",
            name="display_name",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="joblog",
            name="name",
            field=models.CharField(max_length=1000, default="unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasklog",
            name="owner_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("adcm", "adcm"),
                    ("cluster", "cluster"),
                    ("service", "service"),
                    ("component", "component"),
                    ("hostprovider", "hostprovider"),
                    ("host", "host"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        # move data that can be saved
        migrations.RunPython(code=extract_sub_action_data_to_joblogs, reverse_code=do_nothing),
        # make those non-nullable
        migrations.AlterField(
            model_name="stagesubaction",
            name="allow_to_terminate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subaction",
            name="allow_to_terminate",
            field=models.BooleanField(default=False),
        ),
        # because script types weren't correctly defined
        migrations.AlterField(
            model_name="action",
            name="script_type",
            field=models.CharField(
                choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")], max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="stageaction",
            name="script_type",
            field=models.CharField(
                choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")], max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="stagesubaction",
            name="script_type",
            field=models.CharField(
                choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")], max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="subaction",
            name="script_type",
            field=models.CharField(
                choices=[("ansible", "ansible"), ("python", "python"), ("internal", "internal")], max_length=1000
            ),
        ),
        # remove redundant links
        migrations.RemoveField(
            model_name="joblog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="joblog",
            name="log_files",
        ),
        migrations.RemoveField(
            model_name="joblog",
            name="selector",
        ),
        migrations.RemoveField(
            model_name="joblog",
            name="sub_action",
        ),
    ]
