# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-03-27 05:34

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def remove_unlinked_concerns(apps, schema_editor):
    ConcernItem = apps.get_model("cm", "ConcernItem")

    # todo add test on it
    ConcernItem.objects.filter(Q(owner_type__isnull=True) | Q(owner_id__isnull=True)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cm", "0119_delete_MessageTemplate"),
    ]

    operations = [
        migrations.RunPython(code=remove_unlinked_concerns, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="concernitem",
            name="cause",
            field=models.CharField(
                choices=[
                    ("config", "config"),
                    ("job", "job"),
                    ("host-component", "host-component"),
                    ("import", "import"),
                    ("service", "service"),
                    ("requirement", "requirement"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="concernitem",
            name="name",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="concernitem",
            name="owner_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="concernitem",
            name="owner_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.AlterField(
            model_name="concernitem",
            name="type",
            field=models.CharField(
                choices=[("lock", "lock"), ("issue", "issue"), ("flag", "flag")], default="lock", max_length=100
            ),
        ),
        migrations.AddConstraint(
            model_name="concernitem",
            constraint=models.UniqueConstraint(
                fields=("name", "owner_id", "owner_type", "type"), name="cm_concernitem_name_owner_uc"
            ),
        ),
    ]
