# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-04-01 07:21

from django.db import migrations, models


def fill_default_flag_autogeneration_value(apps, schema_editor):
    Prototype = apps.get_model("cm", "Prototype")

    Prototype.objects.all().update(flag_autogeneration={"adcm_outdated_config": False})


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0122_change_concern_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='allow_flags',
        ),
        migrations.RemoveField(
            model_name='stageprototype',
            name='allow_flags',
        ),
        migrations.AddField(
            model_name='prototype',
            name='flag_autogeneration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='stageprototype',
            name='flag_autogeneration',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(code=fill_default_flag_autogeneration_value, reverse_code=migrations.RunPython.noop),
    ]
