# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-04-19 11:46

import functools

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0123_flag_autogeneration_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="multi_state_available",
            field=models.JSONField(default=functools.partial(str, *("any",))),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="before_upgrade",
            field=models.JSONField(default=functools.partial(dict, *((("state", None),),))),
        ),
        migrations.AlterField(
            model_name="clusterobject",
            name="before_upgrade",
            field=models.JSONField(default=functools.partial(dict, *((("state", None),),))),
        ),
        migrations.AlterField(
            model_name="groupconfig",
            name="name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="host",
            name="before_upgrade",
            field=models.JSONField(default=functools.partial(dict, *((("state", None),),))),
        ),
        migrations.AlterField(
            model_name="hostprovider",
            name="before_upgrade",
            field=models.JSONField(default=functools.partial(dict, *((("state", None),),))),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="constraint",
            field=models.JSONField(default=functools.partial(list, *((0, "+"),))),
        ),
        migrations.AlterField(
            model_name="servicecomponent",
            name="before_upgrade",
            field=models.JSONField(default=functools.partial(dict, *((("state", None),),))),
        ),
        migrations.AlterField(
            model_name="stageaction",
            name="multi_state_available",
            field=models.JSONField(default=functools.partial(str, *("any",))),
        ),
        migrations.AlterField(
            model_name="stageprototype",
            name="constraint",
            field=models.JSONField(default=functools.partial(list, *((0, "+"),))),
        ),
        migrations.AlterField(
            model_name="stageupgrade",
            name="from_edition",
            field=models.JSONField(default=functools.partial(list, *(("community",),))),
        ),
        migrations.AlterField(
            model_name="upgrade",
            name="from_edition",
            field=models.JSONField(default=functools.partial(list, *(("community",),))),
        ),
    ]
