# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-06-25 09:36

from django.db import migrations


def activate_statistics_collection(apps, schema_editor):
    ADCM = apps.get_model("cm", "ADCM")
    ConfigLog = apps.get_model("cm", "ConfigLog")

    adcm_object = ADCM.objects.first()
    if adcm_object is None:
        # run on a clean database, no migration required
        return

    adcm_configlog = ConfigLog.objects.get(obj_ref=adcm_object.config, id=adcm_object.config.current)
    attr = adcm_configlog.attr

    if not attr["statistics_collection"]["active"]:
        attr["statistics_collection"]["active"] = True

        adcm_configlog.attr = attr
        adcm_configlog.save(update_fields=["attr"])


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0127_action_host_group"),
    ]

    operations = [migrations.RunPython(code=activate_statistics_collection, reverse_code=migrations.RunPython.noop)]
