# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-09-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0128_activate_statistics_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.JSONField()),
                ("hash", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now=True)),
                ("host", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cm.host")),
            ],
        ),
        migrations.AddIndex(
            model_name="hostinfo",
            index=models.Index(fields=["host"], name="cm_hostinfo_host_id_65bc27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="hostinfo",
            unique_together={("host",)},
        ),
    ]
