# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0130_remove_service_self_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterbind",
            name="service",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="clusterbind",
            name="source_service",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="hostcomponent",
            name="service",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="servicecomponent",
            name="service",
            field=models.IntegerField(),
        ),
    ]
