# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2024-12-05 22:38

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0133_add_is_blocking_and_index_to_tasks"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(django.db.models.functions.text.Lower("name"), name="bundle_lower_name_idx"),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(django.db.models.functions.text.Lower("version"), name="bundle_lower_version_idx"),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(django.db.models.functions.text.Lower("edition"), name="bundle_lower_edition_idx"),
        ),
    ]
