# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-02-03 09:04

from django.db import migrations


def remove_stale_ansibleconfig_actionhostgroup_entries(apps, schema_editor):
    AnsibleConfig = apps.get_model("cm", "AnsibleConfig")
    ActionHostGroup = apps.get_model("cm", "ActionHostGroup")
    Cluster = apps.get_model("cm", "Cluster")
    Service = apps.get_model("cm", "Service")
    Component = apps.get_model("cm", "Component")
    ContentType = apps.get_model("contenttypes", "ContentType")

    cluster_ct = ContentType.objects.get_for_model(Cluster)
    cluster_ids = Cluster.objects.values_list("id", flat=True)

    service_ct = ContentType.objects.get_for_model(Service)
    service_ids = Service.objects.values_list("id", flat=True)

    component_ct = ContentType.objects.get_for_model(Component)
    component_ids = Component.objects.values_list("id", flat=True)

    ct_ids_map = {
        cluster_ct: cluster_ids,
        service_ct: service_ids,
        component_ct: component_ids,
    }

    # only cluster can have ansible_config
    AnsibleConfig.objects.exclude(object_id__in=cluster_ids).delete()

    ahg_delete = set()
    for ct, ids in ct_ids_map.items():
        ahg_delete.add(
            ActionHostGroup.objects.filter(object_type_id=ct.id).exclude(object_id__in=ids).values_list("id", flat=True)
        )

    ActionHostGroup.objects.filter(id__in=ahg_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0134_bundle_bundle_lower_name_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_stale_ansibleconfig_actionhostgroup_entries, reverse_code=migrations.RunPython.noop
        ),
    ]
