# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-09-23 09:29

from django.db import migrations


def fix_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    old_model, new_model = "servicecomponent", "component"

    ContentType.objects.filter(app_label="cm", model=old_model).update(model=new_model)


def reverse_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    old_model, new_model = "component", "servicecomponent"

    ContentType.objects.filter(app_label="cm", model=old_model).update(model=new_model)


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0134_prepare_to_rename_servicecomponent_to_component"),
    ]

    operations = [
        migrations.RenameModel(old_name="ServiceComponent", new_name="Component"),
        migrations.RunPython(code=fix_content_type, reverse_code=reverse_content_type),
    ]
