# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-01-30 16:05

import functools

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0134_bundle_bundle_lower_name_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prototypeconfig",
            name="ansible_options",
            field=models.JSONField(default=functools.partial(dict, *((("unsafe", False),),))),
        ),
        migrations.AddField(
            model_name="stageprototypeconfig",
            name="ansible_options",
            field=models.JSONField(default=functools.partial(dict, *((("unsafe", False),),))),
        ),
    ]
