# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-09-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0135_rename_servicecomponent_to_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostcomponent",
            name="component",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.component"),
        ),
        migrations.AlterField(
            model_name="component",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="components", to="cm.cluster"
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="prototype",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="cm.prototype",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="components", to="cm.service"
            ),
        ),
    ]
