# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-09-25 14:45

from django.db import migrations, models
import django.db.models.deletion


def fix_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    old_model, new_model = "groupconfig", "confighostgroup"

    ContentType.objects.filter(app_label="cm", model=old_model).update(model=new_model)


def reverse_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    old_model, new_model = "confighostgroup", "groupconfig"

    ContentType.objects.filter(app_label="cm", model=old_model).update(model=new_model)


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0137_prepare_to_rename_table_groupconfig"),
    ]

    operations = [
        migrations.RenameModel(old_name="GroupConfig", new_name="ConfigHostGroup"),
        migrations.RunPython(code=fix_content_type, reverse_code=reverse_content_type),
        migrations.AlterField(
            model_name="confighostgroup",
            name="config",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_host_group",
                to="cm.objectconfig",
            ),
        ),
        migrations.AlterField(
            model_name="confighostgroup",
            name="hosts",
            field=models.ManyToManyField(blank=True, related_name="config_host_group", to="cm.Host"),
        ),
        migrations.AlterField(
            model_name="confighostgroup",
            name="object_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
    ]
