# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-05-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0139_add_task_executor_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="objects_related_configs",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="ConfigRevision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("configlog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.configlog")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("configlog",), name="unique_configlog")],
            },
        ),
    ]
