# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-07-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0141_alter_cluster_before_upgrade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="wizard_template",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="stageaction",
            name="wizard_template",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("obejct_id", models.PositiveIntegerField(default=0)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("adcm", "adcm"),
                            ("cluster", "cluster"),
                            ("service", "service"),
                            ("component", "component"),
                            ("provider", "provider"),
                            ("host", "host"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("flow_spec", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hash", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("broken", "broken"),
                            ("revoked", "revoked"),
                            ("finished", "finished"),
                        ],
                        default="created",
                        max_length=100,
                    ),
                ),
                ("action", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cm.action")),
            ],
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, null=True)),
                ("display_name", models.CharField(max_length=150, null=True)),
                ("step_spec", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("running", "running"),
                            ("broken", "broken"),
                            ("revoked", "revoked"),
                            ("failed", "failed"),
                            ("success", "success"),
                            ("aborted", "aborted"),
                        ],
                        default="created",
                        max_length=100,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="cm.process"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="process",
            name="last_completed_step",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_for_process",
                to="cm.processstep",
            ),
        ),
        migrations.CreateModel(
            name="ProcessStepInput",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("configuration", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cm.tasklog")),
                ("step", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cm.processstep")),
            ],
        ),
    ]
