# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0142_action_wizard_template_and_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concernitem",
            name="cause",
            field=models.CharField(
                choices=[
                    ("config", "config"),
                    ("job", "job"),
                    ("host-component", "host-component"),
                    ("import", "import"),
                    ("service", "service"),
                    ("requirement", "requirement"),
                    ("configuring_process", "configuring_process"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
