# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-08-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0143_alter_concernitem_cause"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="original",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicates",
                to="cm.host",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="fqdn",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="host",
            constraint=models.UniqueConstraint(
                condition=models.Q(("original", None)), fields=("fqdn",), name="unique_host_fqdn_with_original"
            ),
        ),
    ]
