# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-09-04 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0144_host_original_alter_host_fqdn_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stageprototype",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="stageprototypeconfig",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="stageprototypeexport",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="stageprototypeimport",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="stageaction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="stageaction",
            name="prototype",
        ),
        migrations.RemoveField(
            model_name="stageprototypeconfig",
            name="action",
        ),
        migrations.RemoveField(
            model_name="stageupgrade",
            name="action",
        ),
        migrations.RemoveField(
            model_name="stageprototype",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="stageprototypeimport",
            name="prototype",
        ),
        migrations.RemoveField(
            model_name="stageprototypeconfig",
            name="prototype",
        ),
        migrations.RemoveField(
            model_name="stageprototypeexport",
            name="prototype",
        ),
        migrations.RemoveField(
            model_name="bundle",
            name="version_order",
        ),
        migrations.RemoveField(
            model_name="prototype",
            name="version_order",
        ),
        migrations.DeleteModel(
            name="StageSubAction",
        ),
        migrations.DeleteModel(
            name="StageAction",
        ),
        migrations.DeleteModel(
            name="StageUpgrade",
        ),
        migrations.DeleteModel(
            name="StagePrototypeImport",
        ),
        migrations.DeleteModel(
            name="StagePrototypeConfig",
        ),
        migrations.DeleteModel(
            name="StagePrototype",
        ),
        migrations.DeleteModel(
            name="StagePrototypeExport",
        ),
    ]
