# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.1.1 on 2025-09-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0146_cluster_uuid_component_uuid_host_uuid_service_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="config_template",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="scripts_template",
            field=models.JSONField(default=None, null=True),
        ),
    ]
