# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2025-12-18 16:44

from collections import defaultdict
from functools import reduce
import logging

from ansible.parsing.vault import VaultAES256, VaultSecret
from django.db import connection, migrations
from django.db.models import Q, Value

ANSIBLE_VAULT_HEADER = "$ANSIBLE_VAULT;1.1;AES256"

log = logging.getLogger("adcm")


def decrypt_empty_strings(apps, schema_editor):
    from django.conf import settings

    secret = settings.ANSIBLE_SECRET
    if not secret:
        message = (
            "Decryption of empty strings in configs is skipped, because ansible secret is undefined. ",
            "If it is your first migration, ignore this message.",
        )
        log.warning(message)
        return

    migration_query = """
    SELECT applied
    FROM django_migrations
    WHERE app='cm' AND name='0146_cluster_uuid_component_uuid_host_uuid_service_uuid'
    """

    res = None
    with connection.cursor() as cursor:
        res = cursor.execute(migration_query).fetchone()

    if not res:
        message = "Decryption of empty strings in configs is skipped, because 2.9 wasn't installed"
        log.info(message)
        return

    first_migration_2_9_date = res[0]

    vault = VaultAES256()
    vault_secret = VaultSecret(_bytes=str(secret).encode("utf-8"))

    def decrypt(value: str) -> str | None:
        _, ciphertext = value.split("\n", maxsplit=1)

        decrypted = vault.decrypt(b_vaulttext=ciphertext, secret=vault_secret)

        if decrypted is None:
            return decrypted

        return decrypted.decode("utf-8")

    PrototypeConfig = apps.get_model("cm", "PrototypeConfig")

    secret_configs = PrototypeConfig.objects.filter(type__in=("password", "secrettext"), action_id__isnull=True)

    proto_param_mapping: dict[int, list] = defaultdict(list)

    for record in secret_configs:
        proto_param_mapping[record.prototype_id].append(record)

    ContentType = apps.get_model("contenttypes", "ContentType")

    Cluster = apps.get_model("cm", "Cluster")
    Service = apps.get_model("cm", "Service")
    Component = apps.get_model("cm", "Component")
    Provider = apps.get_model("cm", "Provider")
    Host = apps.get_model("cm", "Host")

    cluster_ct = ContentType.objects.get_for_model(Cluster)
    service_ct = ContentType.objects.get_for_model(Service)
    component_ct = ContentType.objects.get_for_model(Component)
    provider_ct = ContentType.objects.get_for_model(Provider)
    host_ct = ContentType.objects.get_for_model(Host)

    ConfigHostGroup = apps.get_model("cm", "ConfigHostGroup")

    main_object_queries = [
        model_.objects.filter(prototype_id__in=proto_param_mapping).values_list(
            "config", "prototype_id", "id", Value(ct.pk), Value(model_.__name__.lower())
        )
        for model_, ct in (
            (Cluster, cluster_ct),
            (Service, service_ct),
            (Component, component_ct),
            (Provider, provider_ct),
            (Host, host_ct),
        )
    ]
    union_query = reduce(lambda x, y: x.union(y), main_object_queries)
    main_object_records = tuple(union_query.all())

    object_config_prototype_mapping: dict[int, int] = {
        config_id: prototype_id for config_id, prototype_id, *_ in main_object_records
    }

    grouped_by_ct = defaultdict(list)
    grouped_by_ct_and_object_id = {}

    for _, prototype_id, object_id, object_ct, _ in main_object_records:
        grouped_by_ct[object_ct].append(object_id)
        grouped_by_ct_and_object_id[(object_ct, object_id)] = prototype_id

    chg_object_filter = reduce(
        lambda x, y: x | y,
        (Q(object_type_id=object_ct, object_id__in=object_ids) for object_ct, object_ids in grouped_by_ct.items()),
    )
    chg_query = tuple(
        ConfigHostGroup.objects.filter(chg_object_filter).values_list("config", "object_id", "object_type")
    )

    for config, object_id, object_type in chg_query:
        object_tuple = (object_type, object_id)
        prototype_id = grouped_by_ct_and_object_id.get(object_tuple)
        if prototype_id is not None:
            object_config_prototype_mapping[config] = prototype_id

    ConfigLog = apps.get_model("cm", "ConfigLog")

    config_records = ConfigLog.objects.filter(
        obj_ref_id__in=object_config_prototype_mapping, date__gte=first_migration_2_9_date
    )

    for record in config_records:
        updated = False

        prototype_id = object_config_prototype_mapping[record.obj_ref_id]
        encrypted_parameters = proto_param_mapping[prototype_id]
        for parameter in encrypted_parameters:
            names = list(filter(bool, (parameter.name, *parameter.subname.split("/"))))
            try:
                name, group = _get_group_with_value(names, values=record.config)
            except (KeyError, TypeError):
                log.warning(f"Skipped {names} for {record.pk}")
                continue

            value = group.get(name)
            if isinstance(value, str) and value.startswith(ANSIBLE_VAULT_HEADER):
                decrypted = decrypt(value)
                if decrypted == "":
                    group[name] = ""
                    updated = True

        if updated:
            record.save(update_fields=["config"])


def _get_group_with_value(level_names: list[str], values: dict) -> tuple[str, dict]:
    level_name, *rest = level_names
    if not rest:
        return level_name, values

    return _get_group_with_value(values=values[level_name], level_names=rest)


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0149_processstepinput_mapping"),
    ]

    operations = [
        migrations.RunPython(decrypt_empty_strings),
    ]
