# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2026-01-30 13:53

from django.db import migrations, models

set_names_to_task_update_query = """
UPDATE cm_tasklog
SET
  name=names.action_name,
  display_name=
    CASE
      WHEN names.step_dname IS NOT NULL
        THEN (names.action_dname || ' (' || names.step_dname || ')')
      ELSE names.action_dname
    END
FROM (
    SELECT
      task_t.id as task_id,
      act_t.name as action_name,
      act_t.display_name as action_dname,
      step_t.display_name as step_dname
    FROM cm_tasklog AS task_t
    INNER JOIN cm_action AS act_t ON act_t.id=task_t.action_id
    LEFT JOIN cm_processstep AS step_t ON step_t.id=(task_t.process ->> 'step_id')::int
) AS names
WHERE cm_tasklog.id=names.task_id
"""

truncate_processes_with_relations = """
CREATE TEMP TABLE concern_to_delete
ON COMMIT DROP
AS SELECT id
FROM cm_concernitem
WHERE cause = 'configuring_process';

DELETE FROM cm_adcm_concerns ac
USING concern_to_delete d
WHERE ac.concernitem_id = d.id;

DELETE FROM cm_cluster_concerns cc
USING concern_to_delete d
WHERE cc.concernitem_id = d.id;

DELETE FROM cm_service_concerns sc
USING concern_to_delete d
WHERE sc.concernitem_id = d.id;

DELETE FROM cm_component_concerns cpc
USING concern_to_delete d
WHERE cpc.concernitem_id = d.id;

DELETE FROM cm_provider_concerns pc
USING concern_to_delete d
WHERE pc.concernitem_id = d.id;

DELETE FROM cm_host_concerns hc
USING concern_to_delete d
WHERE hc.concernitem_id = d.id;

UPDATE cm_tasklog ct
SET lock_id = NULL
FROM concern_to_delete d
WHERE ct.lock_id = d.id;

DELETE FROM cm_concernitem ci
USING concern_to_delete d
WHERE ci.id = d.id;

TRUNCATE TABLE
    cm_processstepinput,
    cm_processstep,
    cm_process
RESTART IDENTITY CASCADE;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0150_migrate_empty_string_secrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="type",
            field=models.CharField(
                choices=[("configuration", "configuration"), ("mapping", "mapping"), ("operation", "operation")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="processstep",
            name="stage",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="bundle",
            name="contract_version",
            field=models.CharField(default="1.0", max_length=10),
        ),
        migrations.AddField(
            model_name="configlog",
            name="created_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RenameField(
            model_name="process",
            old_name="object_id",
            new_name="target_id",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="object_type",
            new_name="target_type",
        ),
        migrations.AlterField(
            model_name="process",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("adcm", "adcm"),
                    ("cluster", "cluster"),
                    ("service", "service"),
                    ("component", "component"),
                    ("provider", "provider"),
                    ("host", "host"),
                    ("action-host-group", "action-host-group"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="owner_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="process",
            name="owner_type",
            field=models.CharField(
                choices=[("cluster", "cluster"), ("service", "service"), ("component", "component")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="display_name",
            field=models.CharField(default="-", max_length=1200),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="name",
            field=models.CharField(default="-", max_length=1200),
        ),
        migrations.RunSQL(
            sql=set_names_to_task_update_query,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=truncate_processes_with_relations,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
