# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2025-12-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0151_processstep_type_and_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="contract_version",
            field=models.CharField(default="1.0", max_length=10),
        ),
    ]
