# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2026-02-19 18:18


from collections import defaultdict
from functools import reduce
from pathlib import Path
from typing import Generator, Iterable
import os

from ansible.parsing.vault import shutil
from django.db import migrations, models
from django.db.models import F, Value

PARAMETER_FILE_NAME_SEPARATOR = "."
PARAMETER_NAME_SEPARATOR = "/"
PARAMETER_NAME_ROOT_PREFIX = "/"
IS_ACTIVE = "isActive"
IS_SYNCED = "isSynchronized"


def sync_configs_of_host_groups(apps, schema_editor):
    # Define used models
    ConfigHostGroup = apps.get_model("cm", "ConfigHostGroup")
    Cluster = apps.get_model("cm", "Cluster")
    Service = apps.get_model("cm", "Service")
    Component = apps.get_model("cm", "Component")
    Provider = apps.get_model("cm", "Provider")
    ConfigLog = apps.get_model("cm", "ConfigLog")
    PrototypeConfig = apps.get_model("cm", "PrototypeConfig")

    # can't properly use prefetch on generic key in migration, that's why these complications exist
    model_class_map = {"cluster": Cluster, "service": Service, "component": Component, "provider": Provider}
    class_model_map = {v: k for k, v in model_class_map.items()}

    # Retrieve info about CHGs and their owners

    # find config host groups main info
    host_group_config_id_map = {}
    owner_groups = defaultdict(list)
    required_objects_by_class = defaultdict(list)
    chg_query = ConfigHostGroup.objects.values_list("id", "config__current", "object_id", "object_type__model")
    for group_id, config_id, object_id, object_model_name in chg_query:
        host_group_config_id_map[group_id] = config_id
        owner_groups[(object_model_name, object_id)].append(group_id)
        required_objects_by_class[model_class_map[object_model_name]].append(object_id)

    if not host_group_config_id_map:
        # no configs, no objects, no need to proceed
        return

    # find objects major info and prototype info
    owners_info = {}
    objects_query = reduce(
        lambda left_qs, right_qs: left_qs.union(right_qs),
        (
            class_.objects.values(
                "id",
                "prototype_id",
                model_name=Value(class_model_map[class_]),
                current_config_id=F("config__current"),
            ).filter(id__in=ids)
            for class_, ids in required_objects_by_class.items()
        ),
    )
    for record in objects_query:
        owners_info[(record["model_name"], record["id"])] = record

    # find file parameter names per prototype id
    files_per_prototype: dict[int, set[str]] = {record["prototype_id"]: set() for record in owners_info.values()}

    proto_config_qs = PrototypeConfig.objects.values_list("prototype_id", "name", "subname").filter(
        type__in=("file", "secretfile"), prototype_id__in=files_per_prototype.keys()
    )
    for prototype_id, name, subname in proto_config_qs:
        level_names = filter(bool, (name, *subname.split(PARAMETER_NAME_SEPARATOR)))
        full_name = _ensure_full_name(_level_names_to_full_name(level_names))
        files_per_prototype[prototype_id].add(full_name)

    # Detect base dirs
    base_dir = Path(os.getenv("ADCM_BASE_DIR", Path(__file__).absolute().parent.parent.parent.parent))
    stack_dir = Path(os.getenv("ADCM_STACK_DIR", base_dir))
    file_dir = stack_dir / "data" / "file"
    if not file_dir.is_dir():
        raise RuntimeError(f"Files directory validation failed: {file_dir}")

    # Update configurations

    for owner_key, groups in owner_groups.items():
        owner_model_name, owner_id = owner_key
        owner = owners_info[owner_key]

        main_config_log = ConfigLog.objects.get(id=owner["current_config_id"])
        main_meta = _convert_attr_to_adcm_meta(main_config_log.attr)

        host_group_config_ids = [host_group_config_id_map[chg_id] for chg_id in groups]
        sub_configs = {r.id: r for r in ConfigLog.objects.filter(id__in=host_group_config_ids)}

        prototype_id = owner["prototype_id"]
        file_parameters = files_per_prototype[prototype_id]
        # hacky, but should work
        file_prefix = f"{owner_model_name}.{owner_id}"

        for chg_id in groups:
            any_parameter_updated = False

            group_config_log = sub_configs[host_group_config_id_map[chg_id]]

            group_meta = _convert_attr_to_adcm_meta(group_config_log.attr)
            synced_parameters = ((key, attrs) for key, attrs in group_meta.items() if attrs.get(IS_SYNCED) is True)

            for parameter_full_name, parameter_attrs in synced_parameters:
                group_is_active = parameter_attrs.get(IS_ACTIVE)
                if isinstance(group_is_active, bool):
                    # it's activatable group, should update only attr if required
                    main_is_active = main_meta[parameter_full_name].get(IS_ACTIVE)
                    if main_is_active != group_is_active:
                        parameter_attrs[IS_ACTIVE] = main_is_active
                        any_parameter_updated = True

                    continue

                level_names = _full_name_to_level_names(parameter_full_name)
                # level names are the same in fact
                main_param_name, main_values = _get_group_with_value(level_names, main_config_log.config)
                group_param_name, group_values = _get_group_with_value(level_names, group_config_log.config)
                main_value = main_values[main_param_name]
                group_value = group_values[group_param_name]

                if main_value == group_value:
                    continue

                any_parameter_updated = True
                group_values[group_param_name] = main_value

                if parameter_full_name in file_parameters:
                    param_suffix = _full_name_to_file_name(parameter_full_name)
                    source = file_dir / f"{file_prefix}.{param_suffix}"
                    target = file_dir / f"{file_prefix}.group.{chg_id}.{param_suffix}"

                    # direct file copy to avoid decryption / file specifics
                    shutil.copy(src=str(source.absolute()), dst=str(target.absolute()))

            if any_parameter_updated:
                group_config_log.attr = _convert_adcm_meta_to_attr(group_meta)
                group_config_log.save(update_fields=["config", "attr"])


def _get_group_with_value(level_names: list[str], values: dict) -> tuple[str, dict]:
    level_name, *rest = level_names
    if not rest:
        return level_name, values

    return _get_group_with_value(values=values[level_name], level_names=rest)


def _convert_adcm_meta_to_attr(adcm_meta: dict[str, dict]) -> dict:
    activation = {}
    group_keys = _recursive_defaultdict_on_fields()

    for name, attrs in adcm_meta.items():
        if IS_ACTIVE in attrs:
            activation[name.lstrip("/")] = {"active": attrs[IS_ACTIVE]}

        if IS_SYNCED not in attrs:
            continue

        *groups, own_name = _full_name_to_level_names(name)

        target_node = group_keys

        for group in groups:
            if group not in target_node:
                # "child" came before group
                target_node[group] = {"fields": {}, "value": None}
            elif isinstance(target_node[group], bool):
                # mean previously considered value is actually a group
                target_node[group] = {"fields": {}, "value": target_node[group]}

            target_node = target_node[group]["fields"]

        value_to_set = not attrs[IS_SYNCED]
        if own_name not in target_node:
            target_node[own_name] = value_to_set
        else:
            target_node[own_name]["value"] = value_to_set

    if not group_keys:
        return activation

    return activation | {"group_keys": group_keys}


def _convert_attr_to_adcm_meta(attr: dict) -> dict:
    result = {
        _ensure_full_name(key): {IS_ACTIVE: node["active"]}
        for key, node in attr.items()
        if key not in ("group_keys", "custom_group_keys")
    }

    group_keys = attr.get("group_keys")
    if not group_keys:
        return result

    for name, group_keys_value in _extract_sync_values(group_keys):
        value_to_set = not group_keys_value

        if name in result:
            result[name][IS_SYNCED] = value_to_set
        else:
            result[name] = {IS_SYNCED: value_to_set}

    return result


def _extract_sync_values(node: dict, group: tuple[str, ...] = ()) -> Generator[tuple[str, bool], None, None]:
    for key, value in node.items():
        node_keys = (*group, key)
        if isinstance(value, bool):
            name = _level_names_to_full_name(node_keys)
            yield name, value
        elif isinstance(value, dict):
            group_value = value.get("value")
            if isinstance(group_value, bool):
                name = _level_names_to_full_name(node_keys)
                yield name, group_value

            child_fields = value.get("fields", {})
            if isinstance(child_fields, dict):
                yield from _extract_sync_values(node=child_fields, group=node_keys)


def _ensure_full_name(name: str) -> str:
    name_ = name.rstrip("/")

    if not name_.startswith(PARAMETER_NAME_ROOT_PREFIX):
        return f"{PARAMETER_NAME_ROOT_PREFIX}{name_}"

    return name_


def _level_names_to_full_name(levels: Iterable[str]) -> str:
    return _ensure_full_name(PARAMETER_NAME_SEPARATOR.join(levels))


def _full_name_to_level_names(full: str) -> list[str]:
    return list(filter(bool, full.split(PARAMETER_NAME_SEPARATOR)))


def _full_name_to_file_name(full: str) -> str:
    levels = _full_name_to_level_names(full)
    if len(levels) == 1:
        # backward compatibility
        # first-leveled parameters' names ended with "."
        return f"{levels[0]}{PARAMETER_FILE_NAME_SEPARATOR}"

    return PARAMETER_FILE_NAME_SEPARATOR.join(levels)


def _recursive_defaultdict_on_fields() -> defaultdict:
    return defaultdict(lambda: {"fields": _recursive_defaultdict_on_fields(), "value": None})


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0152_release_2_11_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklog",
            name="severity",
            field=models.CharField(
                choices=[("error", "error"), ("warning", "warning"), ("info", "info")], default="error", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="groupchecklog",
            name="severity",
            field=models.CharField(
                choices=[("error", "error"), ("warning", "warning"), ("info", "info")], default="error", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="processstep",
            name="required",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(code=sync_configs_of_host_groups, reverse_code=migrations.RunPython.noop),
    ]
