# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2025-12-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0153_configlog_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="process",
            old_name="object_id",
            new_name="target_id",
        ),
        migrations.RenameField(
            model_name="process",
            old_name="object_type",
            new_name="target_type",
        ),
        migrations.AlterField(
            model_name="process",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("adcm", "adcm"),
                    ("cluster", "cluster"),
                    ("service", "service"),
                    ("component", "component"),
                    ("provider", "provider"),
                    ("host", "host"),
                    ("action-host-group", "action-host-group"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="owner_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="process",
            name="owner_type",
            field=models.CharField(
                choices=[("cluster", "cluster"), ("service", "service"), ("component", "component")],
                max_length=100,
                null=True,
            ),
        ),
    ]
