# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2026-01-28 09:19

from django.db import migrations, models

set_names_to_task_update_query = """
UPDATE cm_tasklog
SET
  name=names.action_name,
  display_name=
    CASE
      WHEN names.step_dname IS NOT NULL
        THEN (names.action_dname || ' (' || names.step_dname || ')')
      ELSE names.action_dname
    END
FROM (
    SELECT
      task_t.id as task_id,
      act_t.name as action_name,
      act_t.display_name as action_dname,
      step_t.display_name as step_dname
    FROM cm_tasklog AS task_t
    INNER JOIN cm_action AS act_t ON act_t.id=task_t.action_id
    LEFT JOIN cm_processstep AS step_t ON step_t.id=(task_t.process ->> 'step_id')::int
) AS names
WHERE cm_tasklog.id=names.task_id
"""


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0154_extend_process_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="display_name",
            field=models.CharField(default="-", max_length=1200),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="name",
            field=models.CharField(default="-", max_length=1200),
        ),
        migrations.RunSQL(sql=set_names_to_task_update_query, reverse_sql=migrations.RunSQL.noop),
    ]
