# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.14 on 2026-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0154_release_3_0_0"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="config_jinja",
        ),
        migrations.RemoveField(
            model_name="action",
            name="partial_execution",
        ),
        migrations.RemoveField(
            model_name="action",
            name="scripts_jinja",
        ),
        migrations.RemoveField(
            model_name="action",
            name="type",
        ),
    ]
