# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.14 on 2026-08-20 13:48

from collections import defaultdict
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from functools import partial, reduce
from typing import TypeAlias
import operator

from ansible.parsing.vault import VaultAES256, VaultSecret
from django.db import migrations
from django.db.models import F, Q

PrototypeID: TypeAlias = int
ConfigLogID: TypeAlias = int
DecryptorFunc: TypeAlias = Callable[[str], str | None]


ANSIBLE_VAULT_HEADER = "$ANSIBLE_VAULT;1.1;AES256"
CONFIG_FIELDS_DELIMITER = "/"
EMPTY_STR_VALUE = ""


class SecretType(str, Enum):  # values are PrototypeConfig's type db values
    FILE = "secretfile"
    MAP = "secretmap"


@dataclass(slots=True, frozen=True)
class PrototypeConfigData:
    type: SecretType
    name: str
    subname: str
    prototype_id: PrototypeID

    @property
    def key_chain(self) -> list[str]:
        keys = [self.name]
        if self.subname:
            keys.extend(self.subname.split(CONFIG_FIELDS_DELIMITER))

        return keys


def _is_encrypted(value: str) -> bool:
    return value.startswith(ANSIBLE_VAULT_HEADER)


def _decrypt(secret_value: str, vault: VaultAES256, secret: VaultSecret) -> str | None:
    _, ciphertext = secret_value.split("\n", maxsplit=1)

    decrypted = vault.decrypt(b_vaulttext=ciphertext, secret=secret)
    if decrypted is None:
        # for some cases Ansible decryption may return `None` as a valid value
        return decrypted

    return decrypted.decode("utf-8")


def _get_ansible_secret() -> str:
    # Potentially it reaches to external vault if secrets VaultBackend is configured
    from django.conf import settings

    return settings.ANSIBLE_SECRET


def _get_decryptor() -> DecryptorFunc:
    ansible_secret = _get_ansible_secret()

    vault = VaultAES256()
    secret = VaultSecret(_bytes=str(ansible_secret).encode("utf-8"))

    return partial(_decrypt, vault=vault, secret=secret)


def _get_prototype_configs_data(apps) -> set[PrototypeConfigData]:
    PrototypeConfig = apps.get_model("cm", "PrototypeConfig")

    target_secret_types = {stype.value for stype in SecretType}
    pconf_qs = PrototypeConfig.objects.filter(type__in=target_secret_types).values(
        "type", "name", "subname", "prototype_id"
    )

    return {PrototypeConfigData(**pconf) for pconf in pconf_qs}


def _get_objects_configlogs(
    apps,
    prototype_prototype_configs_dict: dict[PrototypeID, set[PrototypeConfigData]],
    container: dict[ConfigLogID, set[PrototypeConfigData]],
) -> None:
    Cluster = apps.get_model("cm", "Cluster")
    Service = apps.get_model("cm", "Service")
    Component = apps.get_model("cm", "Component")
    Provider = apps.get_model("cm", "Provider")
    Host = apps.get_model("cm", "Host")

    object_models = (Cluster, Service, Component, Provider, Host)
    objects_qs = reduce(
        lambda left_qs, right_qs: left_qs.union(right_qs),
        (
            model.objects.values(
                "id", "prototype_id", object_type=F("prototype__type"), current_config_id=F("config__current")
            ).filter(prototype_id__in=prototype_prototype_configs_dict)
            for model in object_models
        ),
    )

    for obj in objects_qs:
        current_config_id = obj["current_config_id"]
        obj_prototype_id = obj["prototype_id"]
        prototype_configs_set = prototype_prototype_configs_dict[obj_prototype_id]

        container[current_config_id].update(prototype_configs_set)


def _get_chg_configlogs(
    apps,
    prototype_prototype_configs_dict: dict[PrototypeID, set[PrototypeConfigData]],
    container: dict[ConfigLogID, set[PrototypeConfigData]],
) -> None:
    ConfigHostGroup = apps.get_model("cm", "ConfigHostGroup")
    Cluster = apps.get_model("cm", "Cluster")
    Service = apps.get_model("cm", "Service")
    Component = apps.get_model("cm", "Component")
    Provider = apps.get_model("cm", "Provider")

    chg_owner_models = (Cluster, Service, Component, Provider)
    chg_owner_candidate_qs = reduce(
        lambda left_qs, right_qs: left_qs.union(right_qs),
        (
            model.objects.values(
                "id",
                "prototype_id",
                object_type=F("prototype__type"),
            ).filter(prototype_id__in=prototype_prototype_configs_dict)
            for model in chg_owner_models
        ),
    )

    object_prototype_dict = {}
    condition = Q()  # CHG's object_type__model == object's prototype__type
    for chg_owner_candidate in chg_owner_candidate_qs:
        condition |= Q(object_id=chg_owner_candidate["id"], object_type__model=chg_owner_candidate["object_type"])
        object_tuple = (chg_owner_candidate["object_type"], chg_owner_candidate["id"])
        object_prototype_dict[object_tuple] = chg_owner_candidate["prototype_id"]

    chg_query = ConfigHostGroup.objects.filter(condition).values(
        "id", current_config_id=F("config__current"), owner_id=F("object_id"), owner_type=F("object_type__model")
    )
    for chg in chg_query:
        current_config_id = chg["current_config_id"]
        object_tuple = (chg["owner_type"], chg["owner_id"])
        obj_prototype_id = object_prototype_dict[object_tuple]
        prototype_configs_set = prototype_prototype_configs_dict[obj_prototype_id]

        container[current_config_id].update(prototype_configs_set)


def _get_current_configlogs(
    apps, prototype_configs: set[PrototypeConfigData]
) -> dict[ConfigLogID, set[PrototypeConfigData]]:
    """Returns ConfigLog's ids and what needs to be rechecked in it (PrototypeConfigs)"""

    prototype_prototype_configs_dict: dict[PrototypeID, set[PrototypeConfigData]] = defaultdict(set)
    for pconfig in prototype_configs:
        prototype_prototype_configs_dict[pconfig.prototype_id].add(pconfig)

    result: dict[ConfigLogID, set[PrototypeConfigData]] = defaultdict(set)
    _get_objects_configlogs(apps, prototype_prototype_configs_dict=prototype_prototype_configs_dict, container=result)
    _get_chg_configlogs(apps, prototype_prototype_configs_dict=prototype_prototype_configs_dict, container=result)

    return result


def _get_updated_configlog_config(
    configlog,
    prototype_configs: set[PrototypeConfigData],
    decryptor: DecryptorFunc,
) -> dict:
    config_dict = configlog.config

    for proto_conf in prototype_configs:
        key_chain = proto_conf.key_chain
        try:
            value = reduce(operator.getitem, key_chain, config_dict)
        except KeyError:  # non-selected selection group case: we do not care about that
            continue

        if value is None:
            continue

        if proto_conf.type == SecretType.FILE:  # content of secretfile is stored in db
            if _is_encrypted(value) and decryptor(value) in {EMPTY_STR_VALUE, None}:
                node = reduce(operator.getitem, key_chain[:-1], config_dict)
                node[key_chain[-1]] = EMPTY_STR_VALUE

        elif proto_conf.type == SecretType.MAP:
            for k, v in value.items():
                if _is_encrypted(v) and decryptor(v) in {EMPTY_STR_VALUE, None}:
                    value[k] = EMPTY_STR_VALUE

        else:
            raise TypeError(f"Unexpected type: {proto_conf.type}")

    return config_dict


def _set_empty(
    apps,
    configlogs: dict[ConfigLogID, set[PrototypeConfigData]],
    decryptor: DecryptorFunc,
) -> None:
    ConfigLog = apps.get_model("cm", "ConfigLog")

    for configlog in ConfigLog.objects.filter(id__in=configlogs):
        prototype_configs = configlogs[configlog.pk]

        configlog.config = _get_updated_configlog_config(
            configlog=configlog,
            prototype_configs=prototype_configs,
            decryptor=decryptor,
        )
        configlog.save(update_fields=["config"])


def set_empty_strings_for_empty_secretfile_and_secretmap_values(apps, schema_editor) -> None:
    _ = schema_editor
    decryptor = _get_decryptor()

    target_prototype_configs = _get_prototype_configs_data(apps)
    target_configlogs: dict[ConfigLogID, set[PrototypeConfigData]] = _get_current_configlogs(
        apps, prototype_configs=target_prototype_configs
    )
    _set_empty(apps, configlogs=target_configlogs, decryptor=decryptor)


class Migration(migrations.Migration):
    dependencies = [
        ("cm", "0154_joblog_executor"),
    ]

    operations = [
        migrations.RunPython(
            code=set_empty_strings_for_empty_secretfile_and_secretmap_values, reverse_code=migrations.RunPython.noop
        ),
    ]
