import { ConfigurationSchema } from '@models/adcm';

export const schema: ConfigurationSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  type: 'object',
  title: 'Primary configuration',
  required: ['cluster_config'],
  adcmMeta: {
    nullValue: null,
    isAdvanced: false,
    isInvisible: false,
    activation: null,
    synchronization: null,
    isSecret: false,
    stringExtra: null,
  },
  properties: {
    cluster_config: {
      type: 'object',
      title: 'Cluster Configuration',
      description: '',
      additionalProperties: false,
      adcmMeta: {
        nullValue: null,
        isAdvanced: false,
        isInvisible: false,
        activation: null,
        synchronization: null,
        isSecret: false,
        stringExtra: null,
      },
      required: [],
      properties: {
        cluster: {
          type: 'array',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: {
              isAllowChange: true,
              isShown: true,
            },
            synchronization: {
              isAllowChange: true,
              isShown: true,
            },
            isSecret: false,
            stringExtra: null,
          },
          items: {
            type: 'object',
            additionalProperties: false,
            adcmMeta: {
              nullValue: null,
              isAdvanced: false,
              isInvisible: false,
              activation: null,
              synchronization: null,
              isSecret: false,
              stringExtra: null,
            },
            required: ['cluster_name'],
            properties: {
              cluster_name: {
                type: 'string',
                default: 'default cluster name',
                adcmMeta: {
                  nullValue: null,
                  isAdvanced: false,
                  isInvisible: false,
                  activation: null,
                  synchronization: null,
                  isSecret: false,
                  stringExtra: null,
                },
              },
              shard: {
                type: 'array',
                default: [],
                adcmMeta: {
                  nullValue: null,
                  isAdvanced: false,
                  isInvisible: false,
                  activation: null,
                  synchronization: null,
                  isSecret: false,
                  stringExtra: null,
                },
                items: {
                  type: 'object',
                  additionalProperties: false,
                  adcmMeta: {
                    nullValue: null,
                    isAdvanced: false,
                    isInvisible: false,
                    activation: null,
                    synchronization: null,
                    isSecret: false,
                    stringExtra: null,
                  },
                  required: ['weight', 'internal_replica', 'replicas'],
                  properties: {
                    weight: {
                      type: 'integer',
                      default: 10,
                      adcmMeta: {
                        nullValue: null,
                        isAdvanced: false,
                        isInvisible: false,
                        activation: null,
                        synchronization: null,
                        isSecret: false,
                        stringExtra: null,
                      },
                    },
                    internal_replica: {
                      type: 'integer',
                      default: 11,
                      adcmMeta: {
                        nullValue: null,
                        isAdvanced: false,
                        isInvisible: false,
                        activation: null,
                        synchronization: null,
                        isSecret: false,
                        stringExtra: null,
                      },
                    },
                    replicas: {
                      type: 'array',
                      default: [{ host: 'test_test' }],
                      adcmMeta: {
                        nullValue: null,
                        isAdvanced: false,
                        isInvisible: false,
                        activation: null,
                        synchronization: null,
                        isSecret: false,
                        stringExtra: null,
                      },
                      items: {
                        type: 'object',
                        additionalProperties: false,
                        adcmMeta: {
                          nullValue: null,
                          isAdvanced: false,
                          isInvisible: false,
                          activation: null,
                          synchronization: null,
                          isSecret: false,
                          stringExtra: null,
                        },
                        required: ['host'],
                        properties: {
                          host: {
                            type: 'string',
                            default: 'default-host',
                            adcmMeta: {
                              nullValue: null,
                              isAdvanced: false,
                              isInvisible: false,
                              activation: null,
                              synchronization: null,
                              isSecret: false,
                              stringExtra: null,
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    test_config: {
      type: 'object',
      required: [],
      adcmMeta: {
        nullValue: null,
        isAdvanced: false,
        isInvisible: false,
        activation: null,
        synchronization: null,
        isSecret: false,
        stringExtra: null,
      },
      properties: {
        someBoolean: {
          type: 'boolean',
          description: 'someBoolean description',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: null,
          },
        },
        someStringWithDefaultValue: {
          type: 'string',
          default: 'default value',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: null,
          },
        },
        someStringWithSuggestions: {
          type: 'string',
          default: 'custom value',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: {
              suggestions: ['One', 'Two', 'Three'],
            },
          },
        },
        someEnum: {
          default: 2,
          enum: ['__one__', 2, '!!!three!!!'],
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            enumExtra: {
              labels: ['One', 'Two', 'Three'],
            },
          },
        },
        someSecretField: {
          type: 'string',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: true,
            stringExtra: null,
          },
        },
        someMultilineField: {
          type: 'string',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
          },
        },
        someJsonField: {
          type: 'string',
          format: 'json',
          default: '{ "default": null, "test": "ddd" }',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
          },
        },
        someYamlField: {
          type: 'string',
          format: 'yaml',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: true,
            stringExtra: {
              isMultiline: true,
            },
          },
        },
        someReadOnlyField: {
          type: 'string',
          readOnly: true,
          format: 'yaml',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
          },
        },
        someAnyOfField: {
          oneOf: [
            {
              type: 'string',
              adcmMeta: {
                nullValue: null,
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                isSecret: false,
                stringExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        someInvisibleField: {
          type: 'string',
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: true,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: null,
          },
        },
        someAdvancedField: {
          type: 'string',
          adcmMeta: {
            nullValue: null,
            isAdvanced: true,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: null,
          },
        },
        someMap: {
          type: 'object',
          required: ['key1'],
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: null,
          },
          additionalProperties: true,
          properties: {
            key1: {
              type: 'string',
              default: 'some default',
              adcmMeta: {
                nullValue: null,
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                isSecret: false,
                stringExtra: null,
              },
            },
          },
        },
        someSecretMap: {
          type: 'object',
          required: [],
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: true,
            stringExtra: null,
          },
          additionalProperties: true,
          properties: {},
        },
        someReadOnlyMap: {
          type: 'object',
          readOnly: true,
          required: ['key1'],
          adcmMeta: {
            nullValue: null,
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            isSecret: false,
            stringExtra: null,
          },
          additionalProperties: true,
          properties: {
            key1: {
              type: 'string',
              readOnly: true,
              default: 'some default',
              adcmMeta: {
                nullValue: null,
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                isSecret: false,
                stringExtra: null,
              },
            },
          },
        },
      },
    },
  },
};
