/* eslint-disable prettier/prettier */
/* eslint-disable spellcheck/spell-checker */
import { ConfigurationSchema } from '@models/adcm';

export const schema: ConfigurationSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'Configuration',
  description: '',
  readOnly: false,
  adcmMeta: {
    isAdvanced: false,
    isInvisible: false,
    activation: null,
    synchronization: null,
    nullValue: null,
    isSecret: false,
    stringExtra: null,
    enumExtra: null,
  },
  type: 'object',
  properties: {
    ansible_host: {
      oneOf: [
        {
          title: 'Connection address',
          type: 'string',
          description: 'Name of the host to connect to',
          default: null,
          readOnly: true,
          adcmMeta: {
            isAdvanced: true,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: false,
            },
            enumExtra: null,
          },
        },
        {
          type: 'null',
        },
      ],
    },
    ansible_port: {
      oneOf: [
        {
          title: 'Port',
          type: 'string',
          description: 'SSH port',
          default: '22',
          readOnly: true,
          adcmMeta: {
            isAdvanced: true,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: false,
            },
            enumExtra: null,
          },
        },
        {
          type: 'null',
        },
      ],
    },
    ansible_user: {
      oneOf: [
        {
          title: 'Username',
          type: 'string',
          description: 'Username used for SSH connection',
          default: 'root',
          readOnly: true,
          adcmMeta: {
            isAdvanced: true,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: false,
            },
            enumExtra: null,
          },
        },
        {
          type: 'null',
        },
      ],
    },
    ansible_ssh_private_key_file: {
      oneOf: [
        {
          title: 'SSH private key',
          type: 'string',
          description: '',
          default: null,
          readOnly: true,
          adcmMeta: {
            isAdvanced: true,
            isInvisible: true,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
            enumExtra: null,
          },
        },
        {
          type: 'null',
        },
      ],
    },
    ansible_become: {
      title: 'Ansible become',
      type: 'boolean',
      description: 'Force privileges escalation?',
      default: true,
      readOnly: true,
      adcmMeta: {
        isAdvanced: true,
        isInvisible: false,
        activation: null,
        synchronization: null,
        nullValue: null,
        isSecret: false,
        stringExtra: null,
        enumExtra: null,
      },
    },
    ansible_ssh_common_args: {
      oneOf: [
        {
          title: 'SSH args',
          type: 'string',
          description: 'Common SSH arguments for Ansible',
          default: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null',
          readOnly: true,
          adcmMeta: {
            isAdvanced: true,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: false,
            },
            enumExtra: null,
          },
        },
        {
          type: 'null',
        },
      ],
    },
    additional_users_groups: {
      oneOf: [
        {
          title: 'Additional users groups',
          type: 'array',
          description:
            'All users created on Init action will be added to this list of groups.\nGroup must be presented in image. One of use cases Altlinux images where\nansible user must be added to "wheel" group.\n',
          default: [],
          readOnly: false,
          adcmMeta: {
            isAdvanced: true,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: [],
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
          items: {
            type: 'string',
            title: '',
            description: '',
            default: null,
            readOnly: false,
            adcmMeta: {
              isAdvanced: false,
              isInvisible: false,
              activation: null,
              synchronization: null,
              nullValue: null,
              isSecret: false,
              stringExtra: null,
              enumExtra: null,
            },
          },
        },
        {
          type: 'null',
        },
      ],
    },
    instance: {
      title: 'instance',
      type: 'object',
      description: '',
      default: {},
      readOnly: false,
      adcmMeta: {
        isAdvanced: false,
        isInvisible: false,
        activation: null,
        synchronization: null,
        nullValue: null,
        isSecret: false,
        stringExtra: null,
        enumExtra: null,
      },
      additionalProperties: false,
      properties: {
        login: {
          oneOf: [
            {
              title: 'Login',
              type: 'string',
              description: 'User which will be created for VM',
              default: null,
              readOnly: true,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: false,
                },
                enumExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        ssh_key: {
          oneOf: [
            {
              title: 'Public SSH key',
              type: 'string',
              description: '',
              default: null,
              readOnly: true,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: true,
                },
                enumExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        timeout: {
          oneOf: [
            {
              title: 'Cloud-init timeout',
              type: 'integer',
              description: 'Timeout for cloud-init to finish running tasks, in seconds',
              default: 600,
              readOnly: false,
              adcmMeta: {
                isAdvanced: true,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: null,
                enumExtra: null,
              },
              minimum: 0,
            },
            {
              type: 'null',
            },
          ],
        },
        init_script: {
          oneOf: [
            {
              title: 'Init script',
              type: 'string',
              description:
                'Init script to be executed on vm deployment. Shebang is not needed\nExperimental option single or double quote may broke "Install" function.\n',
              default: null,
              readOnly: false,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: true,
                },
                enumExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        image_family: {
          title: 'Image family',
          type: 'string',
          description: '',
          default: 'centos-7',
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: false,
              suggestions: ['centos-7', 'centos-stream-8', 'ubuntu-1804-lts', 'debian-10'],
            },
            enumExtra: null,
          },
        },
        template: {
          title: 'Image',
          description:
            'Mutually exclusive option with advanced option "Image id" and "Snapshot id".\nImage id and Snapshot id have higher priority\n',
          default: 'fd8u8t05uet8frke86tb',
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: true,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
            enumExtra: {
              labels: ['CentOS 7', 'Ubuntu 18', 'Windows 2016'],
            },
          },
          enum: ['fd8u8t05uet8frke86tb', 'fd83bj827tp2slnpp7f0', 'fd8hph1ebp3md34nmo2v'],
        },
        snapshotId: {
          oneOf: [
            {
              title: 'Snapshot id',
              type: 'string',
              description:
                'Mutually exclusive option with "Image" and "Image id".\nIf filled "Image" and "Image id" fields are ignored.\nIf "Image id" and "Snapshot id" are both filled then an error will be raised.\n',
              default: null,
              readOnly: false,
              adcmMeta: {
                isAdvanced: true,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: false,
                },
                enumExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        imageId: {
          oneOf: [
            {
              title: 'Image id',
              type: 'string',
              description:
                'Mutually exclusive option with "Image" and "Snapshot id".\nIf filled "Image" and "Snapshot id" fields are ignored.\nIf "Image id" and "Snapshot id" are both filled then an error will be raised.\n',
              default: null,
              readOnly: false,
              adcmMeta: {
                isAdvanced: true,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: false,
                },
                enumExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        usersGroups: {
          oneOf: [
            {
              title: 'Additional users groups',
              type: 'array',
              description:
                'All users created on Init action will be added to this list of groups.\nGroup must be presented in image.\n',
              default: [],
              readOnly: false,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: true,
                activation: null,
                synchronization: null,
                nullValue: [],
                isSecret: false,
                stringExtra: null,
                enumExtra: null,
              },
              items: {
                type: 'string',
                title: '',
                description: '',
                default: null,
                readOnly: false,
                adcmMeta: {
                  isAdvanced: false,
                  isInvisible: false,
                  activation: null,
                  synchronization: null,
                  nullValue: null,
                  isSecret: false,
                  stringExtra: null,
                  enumExtra: null,
                },
              },
            },
            {
              type: 'null',
            },
          ],
        },
        platformId: {
          title: 'Platform',
          description:
            'Yandex supported platforms, more information - https://cloud.yandex.ru/docs/compute/concepts/vm-platforms',
          default: 'standard-v2',
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
            enumExtra: {
              labels: ['Intel Broadwell', 'Intel Cascade Lake', 'Intel Ice Lake'],
            },
          },
          enum: ['standard-v1', 'standard-v2', 'standard-v3'],
        },
        cpu: {
          title: 'vCPU',
          type: 'integer',
          description: 'Number of vCPU',
          default: 2,
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
          minimum: 1,
          maximum: 256,
        },
        coreFraction: {
          title: 'Perfomance level (%)',
          description: 'Yandex vm perfomance level - https://cloud.yandex.ru/docs/compute/concepts/performance-levels',
          default: 100,
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
            enumExtra: {
              labels: ['5', '20', '50', '100'],
            },
          },
          enum: [5, 20, 50, 100],
        },
        memory: {
          title: 'Memory (GB)',
          type: 'integer',
          description: 'RAM',
          default: 2,
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
          minimum: 1,
          maximum: 256,
        },
        disk_type: {
          title: 'Disk type',
          description: 'Storage class of VM',
          default: 'network-hdd',
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
            enumExtra: {
              labels: ['SSD', 'HDD', 'SSD-NONREPLICATED'],
            },
          },
          enum: ['network-ssd', 'network-hdd', 'network-ssd-nonreplicated'],
        },
        disk_size: {
          title: 'Disk size, GB',
          type: 'integer',
          description: 'The size of the boot disk created for this instance',
          default: 50,
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
        },
        additional_disks: {
          oneOf: [
            {
              title: 'Additional disks (JSON)\n',
              type: 'string',
              description:
                'Specify the size in GB,\nall parameters are required !\nExample:\n[{\n    "autodelete": true,\n    "description": "disk1",\n    "type": "ssd",\n    "size": 10\n},\n{\n    "autodelete": false,\n    "description": "disk2",\n    "type": "hdd",\n    "size": 100\n}]\n',
              default: 'null',
              readOnly: false,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: true,
                },
                enumExtra: null,
              },
              format: 'json',
            },
            {
              type: 'null',
            },
          ],
        },
        assign_public_ip: {
          title: 'Assign public ip',
          type: 'boolean',
          description: '',
          default: false,
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
        },
        assign_internal_ip: {
          oneOf: [
            {
              title: 'Assign internal ip',
              type: 'string',
              description: '',
              default: null,
              readOnly: false,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: null,
                isSecret: false,
                stringExtra: {
                  isMultiline: false,
                },
                enumExtra: null,
              },
            },
            {
              type: 'null',
            },
          ],
        },
        security_groups: {
          oneOf: [
            {
              title: 'Security Group IDs',
              type: 'array',
              description:
                'All SGs added on Init action will be attached to VM\'s network interface.\nGroup must be presented in VPC.\n',
              default: [],
              readOnly: false,
              adcmMeta: {
                isAdvanced: false,
                isInvisible: false,
                activation: null,
                synchronization: null,
                nullValue: [],
                isSecret: false,
                stringExtra: null,
                enumExtra: null,
              },
              items: {
                type: 'string',
                title: '',
                description: '',
                default: null,
                readOnly: false,
                adcmMeta: {
                  isAdvanced: false,
                  isInvisible: false,
                  activation: null,
                  synchronization: null,
                  nullValue: null,
                  isSecret: false,
                  stringExtra: null,
                  enumExtra: null,
                },
              },
            },
            {
              type: 'null',
            },
          ],
        },
        labels: {
          title: 'Labels',
          type: 'object',
          description: 'Key:value instance labels',
          default: {},
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: {},
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
          additionalProperties: true,
          properties: {},
        },
        preemptible: {
          title: 'Preemptible',
          type: 'boolean',
          description:
            'VM that works not more than 24 hour. May be interrapted at any time.\nOffered with big discount. May be defined only before initialization.\n',
          default: false,
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
        },
        control_address_type: {
          title: 'ADCM control connection address type',
          description: 'IP address (public or private) to communicate with the host',
          default: 'private',
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: null,
            isSecret: false,
            stringExtra: {
              isMultiline: true,
            },
            enumExtra: {
              labels: ['private', 'public'],
            },
          },
          enum: ['private', 'public'],
        },
      },
      required: [
        'login',
        'ssh_key',
        'timeout',
        'init_script',
        'image_family',
        'template',
        'snapshotId',
        'imageId',
        'usersGroups',
        'platformId',
        'cpu',
        'coreFraction',
        'memory',
        'disk_type',
        'disk_size',
        'additional_disks',
        'assign_public_ip',
        'assign_internal_ip',
        'security_groups',
        'labels',
        'preemptible',
        'control_address_type',
      ],
    },
  },
  additionalProperties: false,
  required: [
    'ansible_host',
    'ansible_port',
    'ansible_user',
    'ansible_ssh_private_key_file',
    'ansible_become',
    'ansible_ssh_common_args',
    'additional_users_groups',
    'instance',
  ],
};

export const schema2: ConfigurationSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'Configuration',
  description: '',
  readOnly: false,
  adcmMeta: {
    isAdvanced: false,
    isInvisible: false,
    activation: null,
    synchronization: null,
    nullValue: null,
    isSecret: false,
    stringExtra: null,
    enumExtra: null,
  },
  type: 'object',
  properties: {
    instance: {
      title: 'instance',
      type: 'object',
      description: '',
      default: {},
      readOnly: false,
      adcmMeta: {
        isAdvanced: false,
        isInvisible: false,
        activation: null,
        synchronization: null,
        nullValue: null,
        isSecret: false,
        stringExtra: null,
        enumExtra: null,
      },
      additionalProperties: false,
      properties: {
        nullableObject: {
          title: 'Nullable object',
          type: 'object',
          description: 'Key:value instance labels',
          default: {},
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: {},
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
          additionalProperties: true,
          properties: {},
        },
        nullableArray: {
          title: 'Nullable array',
          type: 'array',
          description: 'Key:value instance labels',
          default: {},
          readOnly: false,
          adcmMeta: {
            isAdvanced: false,
            isInvisible: false,
            activation: null,
            synchronization: null,
            nullValue: {},
            isSecret: false,
            stringExtra: null,
            enumExtra: null,
          },
          items: {
            type: 'string',
            title: '',
            description: '',
            default: null,
            readOnly: false,
            adcmMeta: {
              isAdvanced: false,
              isInvisible: false,
              activation: null,
              synchronization: null,
              nullValue: null,
              isSecret: false,
              stringExtra: null,
              enumExtra: null,
            },
          },
        },
      },
      required: [
        'nullableObject',
        'nullableArray',
      ],
    },
  },
  additionalProperties: false,
  required: [
    'instance',
  ],
};
