#!/bin/sh

. /etc/adcmenv

waitforwsgi

if { [ -z "$FEATURE_JOB_SCHEDULER" ] || [ "$FEATURE_JOB_SCHEDULER" != "old" ] ; } && { [ -z "$MIGRATION_MODE" ] || [ "$MIGRATION_MODE" -ne 1 ]; }
then
    echo "Run scheduler ... "
    exec "${adcmroot}/python/jobs/scheduler/run.py"
fi
