#!/bin/sh
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /etc/adcmenv

waitforinit

echo "Run main wsgi application ..."
exec 1>>"${adcmlog}/service_wsgi.out"
exec 2>>"${adcmlog}/service_wsgi.err"

cd "${adcmroot}/python"
touch /run/uwsgi.pid
uwsgi --ini /etc/adcm/adcm.cfg
