# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2026-03-10 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("audit", "0001_initial"),
        ("audit", "0002_alter_auditobject_object_type"),
        ("audit", "0003_auto_20230124_0849"),
        ("audit", "0004_auto_20230131_0944"),
        ("audit", "0005_audit_user"),
        ("audit", "0006_add_address"),
        ("audit", "0007_add_agent"),
        ("audit", "0008_action_host_group"),
    ]
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("object_name", models.CharField(max_length=2000)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("prototype", "prototype"),
                            ("cluster", "cluster"),
                            ("service", "service"),
                            ("component", "component"),
                            ("host", "host"),
                            ("provider", "provider"),
                            ("bundle", "bundle"),
                            ("adcm", "adcm"),
                            ("user", "user"),
                            ("group", "group"),
                            ("role", "role"),
                            ("policy", "policy"),
                            ("action-host-group", "action-host-group"),
                        ],
                        max_length=2000,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AuditUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150)),
                ("auth_user_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "login_result",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("wrong password", "wrong password"),
                            ("account disabled", "account disabled"),
                            ("user not found", "user not found"),
                        ],
                        max_length=2000,
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("login_details", models.JSONField(default=dict, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("agent", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.audituser"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_name", models.CharField(max_length=2000)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("create", "create"), ("update", "update"), ("delete", "delete")], max_length=2000
                    ),
                ),
                (
                    "operation_result",
                    models.CharField(
                        choices=[("success", "success"), ("fail", "fail"), ("denied", "denied")], max_length=2000
                    ),
                ),
                ("operation_time", models.DateTimeField(auto_now_add=True)),
                ("object_changes", models.JSONField(default=dict)),
                ("address", models.CharField(max_length=255, null=True)),
                ("agent", models.CharField(blank=True, default="", max_length=255)),
                (
                    "audit_object",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.auditobject"),
                ),
                (
                    "user",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.audituser"),
                ),
            ],
        ),
    ]
