# Generated by Django 3.2.13 on 2022-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsession',
            name='login_details',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
