# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.23 on 2024-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0007_add_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("prototype", "prototype"),
                    ("cluster", "cluster"),
                    ("service", "service"),
                    ("component", "component"),
                    ("host", "host"),
                    ("provider", "provider"),
                    ("bundle", "bundle"),
                    ("adcm", "adcm"),
                    ("user", "user"),
                    ("group", "group"),
                    ("role", "role"),
                    ("policy", "policy"),
                    ("action-host-group", "action-host-group"),
                ],
                max_length=2000,
            ),
        ),
    ]
