import type { SchemaDefinition } from '@models/adcm';

export const configurationValidationSchema: SchemaDefinition = {
  title: 'Configuration',
  type: 'object',
  readOnly: false,
  additionalProperties: false,
  required: ['my_password', 'my_list_variant', 'my_group_with_required_not_default_parameters', 'my_activatable_group'],
  properties: {
    my_password: {
      title: 'my_password',
      type: 'string',
      default: null,
      readOnly: false,
      minLength: 1,
      adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: true },
    },
    my_list_variant: {
      title: 'my_list_variant',
      type: 'string',
      default: null,
      readOnly: false,
      enum: ['value1', 'value2', 'value3'],
      adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
    },
    my_group_with_required_not_default_parameters: {
      title: 'my_group_with_required_not_default_parameters',
      type: 'object',
      default: {},
      readOnly: false,
      additionalProperties: false,
      required: [
        'my_boolean',
        'my_float',
        'my_integer',
        'my_list',
        'my_map',
        'my_string',
        'my_text',
        'my_json',
        'my_file',
        'my_password',
        'secrettext',
        'my_builtin_variant',
        'my_list_variant',
        'my_inline_variant_not_strict',
        'my_inline_variant_strict',
      ],
      properties: {
        my_boolean: {
          title: 'my_boolean',
          type: 'boolean',
          default: null,
          readOnly: false,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_float: {
          title: 'my_float',
          type: 'number',
          default: null,
          readOnly: false,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_integer: {
          title: 'my_integer',
          type: 'integer',
          default: null,
          readOnly: false,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_list: {
          title: 'my_list',
          type: 'array',
          default: [],
          readOnly: false,
          items: { type: 'string', default: null, readOnly: false },
          minItems: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_map: {
          title: 'my_map',
          type: 'object',
          default: {},
          readOnly: false,
          additionalProperties: true,
          properties: {},
          minProperties: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_string: {
          title: 'my_string',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_text: {
          title: 'my_text',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_json: {
          title: 'my_json',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          format: 'json',
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_file: {
          title: 'my_file',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_password: {
          title: 'my_password',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: true },
        },
        secrettext: {
          title: 'secrettext',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: true },
        },
        my_builtin_variant: {
          title: 'my_builtin_variant',
          default: null,
          readOnly: false,
          enum: [null],
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_list_variant: {
          title: 'my_list_variant',
          default: null,
          readOnly: false,
          enum: ['value1', 'value2', 'value3'],
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_inline_variant_not_strict: {
          title: 'my_inline_variant_not_strict',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
        my_inline_variant_strict: {
          title: 'my_inline_variant_strict',
          default: null,
          readOnly: false,
          enum: ['Moscow', 'Ufa', 'SPB'],
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
        },
      },
      adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
    },
    my_activatable_group: {
      title: 'my_activatable_group',
      type: 'object',
      default: {},
      readOnly: false,
      additionalProperties: false,
      required: [
        'my_boolean',
        'my_float',
        'my_integer',
        'my_string',
        'my_text',
        'json',
        'my_file',
        'my_password',
        'secrettext',
      ],
      properties: {
        my_boolean: { title: 'my_boolean', type: 'boolean', default: true, readOnly: true },
        my_float: { title: 'my_float', type: 'number', default: 0.1, readOnly: false },
        my_integer: { title: 'my_integer', type: 'integer', default: 10, readOnly: false },
        my_string: { title: 'my_string', type: 'string', default: 'string', readOnly: false },
        my_text: { title: 'my_text', type: 'string', default: 'text', readOnly: false },
        json: { title: 'json', type: 'string', default: '{"key": "value"}', readOnly: false, format: 'json' },
        my_file: { title: 'my_file', type: 'string', default: 'my file content\n', readOnly: false },
        my_password: {
          title: 'my_password',
          type: 'string',
          default: null,
          readOnly: false,
          minLength: 1,
          adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: true },
        },
        secrettext: {
          title: 'secrettext',
          type: 'string',
          default: null,
          readOnly: false,
          adcmMeta: { isSecret: true },
        },
      },
      adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
    },
  },
  adcmMeta: { isAdvanced: false, isInvisible: false, isSecret: false },
  $schema: 'https://json-schema.org/draft/2020-12/schema',
};
