# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 5.2.7 on 2026-03-10 14:31

from django.conf import settings
from django.db import migrations, models
import django.contrib.auth.models


class Migration(migrations.Migration):
    replaces = [
        ("rbac", "0001_initial"),
        ("rbac", "0002_rm_default_policy"),
        ("rbac", "0003_user_group_origin_type"),
        ("rbac", "0004_fill_group_name_display_name"),
        ("rbac", "0005_rbac_group_unique_display_name_type_constraint"),
        ("rbac", "0006_auto_20220928_0455"),
        ("rbac", "0007_auto_20230124_0849"),
        ("rbac", "0008_auto_20230320_1312"),
        ("rbac", "0009_auto_20230227_1639"),
        ("rbac", "0010_rename_login_attempts_user_failed_login_attempts"),
        ("rbac", "0011_user_last_failed_login_at"),
        ("rbac", "0012_delete_inactive_users"),
        ("rbac", "0013_auto_20230628_1342"),
        ("rbac", "0014_alter_group_description"),
        ("rbac", "0015_make_admin_not_builtin"),
        ("rbac", "0016_fix_roles_after_rename_models"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cm", "0001_squashed_0151_release_2_10_0"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("guardian", "0002_generic_permissions_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleMigration",
            fields=[
                ("version", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("profile", models.JSONField(default=str)),
                ("built_in", models.BooleanField(default=False)),
                ("failed_login_attempts", models.SmallIntegerField(default=0)),
                ("blocked_at", models.DateTimeField(null=True)),
                ("last_failed_login_at", models.DateTimeField(null=True)),
                (
                    "type",
                    models.CharField(choices=[("local", "local"), ("ldap", "ldap")], default="local", max_length=1000),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("description", models.CharField(default="", max_length=1000)),
                ("built_in", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(choices=[("local", "local"), ("ldap", "ldap")], default="local", max_length=1000),
                ),
                ("display_name", models.CharField(max_length=1000, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("display_name", "type"), name="unique_display_name_type")
                ],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="PolicyObject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="rbac.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="rbac.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("display_name", models.CharField(default="", max_length=1000)),
                ("module_name", models.CharField(max_length=1000)),
                ("class_name", models.CharField(max_length=1000)),
                ("init_params", models.JSONField(default=dict)),
                ("built_in", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("business", "business"), ("role", "role"), ("hidden", "hidden")],
                        default="role",
                        max_length=1000,
                    ),
                ),
                ("any_category", models.BooleanField(default=False)),
                ("parametrized_by_type", models.JSONField(default=list)),
                (
                    "bundle",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="cm.bundle"
                    ),
                ),
                ("category", models.ManyToManyField(to="cm.productcategory")),
                ("child", models.ManyToManyField(blank=True, to="rbac.role")),
                ("permissions", models.ManyToManyField(blank=True, to="auth.permission")),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("description", models.TextField(blank=True)),
                ("built_in", models.BooleanField(default=True)),
                ("group", models.ManyToManyField(to="rbac.group")),
                ("group_object_perm", models.ManyToManyField(blank=True, to="guardian.groupobjectpermission")),
                ("object", models.ManyToManyField(blank=True, to="rbac.policyobject")),
                ("model_perm", models.ManyToManyField(blank=True, to="rbac.policypermission")),
                ("role", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="rbac.role")),
            ],
        ),
        migrations.AddConstraint(
            model_name="policyobject",
            constraint=models.UniqueConstraint(fields=("content_type", "object_id"), name="unique_policy_object"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name", "display_name"], name="rbac_role_name_b010fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("name", "built_in"), name="unique_name"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("display_name", "built_in"), name="unique_display_name"),
        ),
    ]
