# Generated by Django 3.2.13 on 2022-06-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_rm_default_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(
                choices=[('local', 'local'), ('ldap', 'ldap')], default='local', max_length=16
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(
                choices=[('local', 'local'), ('ldap', 'ldap')], default='local', max_length=16
            ),
        ),
    ]
