# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 3.2 on 2021-11-26 14:28

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models, connection


def upgrade_users(apps, schema_editor):
    query = '''
            INSERT INTO "rbac_user" ("user_ptr_id", "profile")
            SELECT au.id, coalesce(up.profile, "{}")
                FROM "auth_user" au
                LEFT JOIN "rbac_user" ru ON ru.user_ptr_id = au.id
                LEFT JOIN "cm_userprofile" up ON au.username = up.login
                WHERE ru.user_ptr_id IS NULL
        '''
    with connection.cursor() as cursor:
        cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rbac', '0004_auto_20211125_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'user_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='auth.user',
                    ),
                ),
                ('profile', models.JSONField(default=str)),
                ('group', models.ManyToManyField(related_name='user', to='rbac.Group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(upgrade_users),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='policy',
            name='user',
            field=models.ManyToManyField(blank=True, to='rbac.User'),
        ),
        migrations.AddField(
            model_name='policy',
            name='built_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='policypermission',
            name='user',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.user'
            ),
        ),
    ]
