# Generated by Django 3.2.13 on 2022-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_fill_group_name_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_unjoined',
            field=models.DateTimeField(null=True),
        ),
    ]
