# Generated by Django 3.2.13 on 2022-07-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_fill_group_name_display_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(
                fields=('display_name', 'type'), name='unique_display_name_type'
            ),
        ),
    ]
