# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.4 on 2021-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20211201_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='business_permit',
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(
                choices=[('business', 'business'), ('role', 'role'), ('hidden', 'hidden')],
                default='role',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(default='', max_length=160),
        ),
    ]
