# Generated by Django 3.2.4 on 2021-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20211201_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='business_permit',
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(
                choices=[('business', 'business'), ('role', 'role'), ('hidden', 'hidden')],
                default='role',
                max_length=32,
            ),
        ),
    ]
