# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2 on 2021-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20211203_1018'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name', 'display_name'], name='rbac_role_name_b010fa_idx'),
        ),
        migrations.RunSQL(
            '''
            CREATE INDEX auth_user_name_b010fa_idx
            ON auth_user (username, first_name, last_name, email);
        '''
        ),
        migrations.RunSQL(
            '''
            CREATE INDEX auth_group_name_b010fa_idx
            ON auth_group (name);
        '''
        ),
    ]
