# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.16 on 2023-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0008_auto_20230320_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_attempts",
            field=models.SmallIntegerField(default=0),
        ),
    ]
