# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.18 on 2023-04-07 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0009_auto_20230227_1639"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="login_attempts",
            new_name="failed_login_attempts",
        ),
    ]
