# Generated by Django 3.2.4 on 2021-12-23 20:47

from django.db import migrations, models


def check_name(apps, schema_editor):
    Role = apps.get_model('rbac', 'Role')
    for role in Role.objects.all():
        if len(Role.objects.filter(name=role.name, built_in=role.built_in)) > 1:
            role.delete()


def check_display_name(apps, schema_editor):
    Role = apps.get_model('rbac', 'Role')
    for role in Role.objects.all():
        if len(Role.objects.filter(display_name=role.display_name, built_in=role.built_in)) > 1:
            role.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_upd_role_category'),
    ]

    operations = [
        migrations.RunPython(check_name),
        migrations.RunPython(check_display_name),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role',
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name', 'built_in'), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(
                fields=('display_name', 'built_in'), name='unique_display_name'
            ),
        ),
    ]
