# Generated by Django 3.2 on 2021-12-29 07:02

from django.db import migrations, models


def update_status_user(apps, schema_editor):
    User = apps.get_model('rbac', 'User')
    status_user = User.objects.filter(username='status').first()
    if status_user:
        status_user.built_in = True
        status_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20211223_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='built_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='built_in',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_status_user),
    ]
