# Generated by Django 3.2 on 2021-12-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20211223_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
