# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 3.2.19 on 2023-06-26 13:30

from django.db import migrations


def delete_inactive_users(apps, schema_editor) -> None:
    RBACUser = apps.get_model("rbac", "User")
    RBACUser.objects.filter(is_active=False).delete()


def delete_inactive_users_reverse(apps, schema_editor) -> None:
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0011_user_last_failed_login_at"),
    ]

    operations = [
        migrations.RunPython(code=delete_inactive_users, reverse_code=delete_inactive_users_reverse),
    ]
