@startuml host
title
Requests for Host page
end title

skinparam BoxPadding 10

database HTTP

box "Host list"
collections "Host list" as list
endbox

box "Form for add Host"
collections Clusters
collections "Host from stack" as stack
actor "Add new host" as sh
endbox

box "Configuration"
collections "Fields config" as cf
collections History as ch
actor "Save config" as cs
endbox

== Initialization ==

HTTP -> list: "GET /api/v1/host/"
activate HTTP
HTTP -> Clusters: "GET /api/v1/cluster/"
HTTP -> stack: "GET /api/v1/stack/host/"
deactivate HTTP

||40||

== Add host ==

sh -> HTTP: "POST /api/v1/host/"
activate sh 
activate HTTP
Clusters --> sh: Internal request if had select cluster
activate sh
sh --> HTTP:  "POST /api/v1/cluster/{cluster_id}/host/"
deactivate sh
HTTP -> sh
deactivate sh
HTTP -> list: "GET /api/v1/host/"
deactivate HTTP

||40||

== Configuration ==
list -> cf: "GET /api/v1/host/{host_id}/config/?view=interface"
activate list
list -> ch: "GET /api/v1/host/{host_id}/config/history/"
deactivate list

cs -> HTTP: "POST /api/v1/host/{host_id}/config/?view=interface"
activate cs
activate HTTP
HTTP --> cf: "GET /api/v1/host/{host_id}/config/?view=interface"
activate HTTP
HTTP --> ch: "GET /api/v1/host/{host_id}/config/history/"
deactivate HTTP
HTTP -> cs
deactivate HTTP
deactivate cs

ch -> HTTP: "Change history"
activate ch
activate HTTP
HTTP --> cf: "GET /api/v1/host/{host_id}/config/?view=interface"
activate HTTP
HTTP --> ch: "GET /api/v1/host/{host_id}/config/history/"
deactivate HTTP
HTTP -> ch
deactivate HTTP
deactivate ch

||40||

== Actions ==

box "Actions"
collections "Actions" as act
endbox

list -> act: "GET /api/v1/host/{host_id}/action/"
act -> HTTP: "POST /api/v1/cluster/{host_id}/action/{action_id}/run/"

||40||
@enduml