#
# Arenadata documentation build configuration file, created by
# sphinx-quickstart on Mon Jul 31 16:56:10 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

from string import Template
import datetime

# import sphinx_markdown_tables
import sphinx_rtd_theme

# -- General configuration ------------------------------------------------

# git rev-parse --abbrev-ref HEAD
version = ""  # substituted via -D option
# The full version, including alpha/beta/rc tags.
release = version

now = datetime.datetime.now()  # noqa: DTZ005


title = Template(
    r"""
            \pagenumbering{Roman} %%% to avoid page 1 conflict with actual page 1
            \begin{titlepage}

                \vspace*{-31.4mm}
                \begin{center}
                  \makebox[\textwidth]{\includegraphics[width=\paperwidth]{logo.png}}
                \end{center}

                \raggedright

                \vspace*{70mm} %%% * is used to give space from top
                \textbf{\Huge {Arenadata™ #title#}}

                \vspace*{30mm}
                \Large \textit{Версия - $version}

                \LARGE \textbf{{#name#}}

                %% \vfill adds at the bottom
                \vfill
                \normalsize \textit{ $pusblish Arenadata™}
            \end{titlepage}
            \pagenumbering{arabic}
            \tableofcontents
            \clearpage
            """
).substitute({"pusblish": now.year, "version": version})

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "sphinx.ext.extlinks",
    "sphinx_markdown_tables",
    # "sphinxpapyrus.docxbuilder",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#

source_parsers = {
    ".md": "recommonmark.parser.CommonMarkParser",
}

source_suffix = {
    ".rst": "restructuredtext",
    ".txt": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# General information about the project.


project = "Arenadata Cluster Manager Specs"
copyright = "{}, Arenadata.io".format(now.year)  # noqa: A001, UP032
author = "Arenadata.io"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set 'language' from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named 'default.css' will overwrite the builtin 'default.css'.
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "about.html",
        "navigation.html",
        "relations.html",  # needs 'show_related': True theme option to display
        "searchbox.html",
        "donate.html",
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "Arenadatadoc"

today = "{}, Arenadata™".format(now.year)  # noqa: UP032
latex_keep_old_macro_names = True

latex_logo = "_static/logo.png"

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
    "classoptions": ",openany,oneside",  # Removes blank pages
    # VerbatimColor - background color of codeblocks
    "sphinxsetup": "TitleColor={rgb}{0.05, 0.5, 0.06}, InnerLinkColor={rgb}{0.05, 0.5, 0.06},\
                    VerbatimColor={rgb}{0.82, 0.94, 0.75}, importantBorderColor={rgb}{0.66, 0.89, 0.63},\
                    OuterLinkColor={rgb}{0.04, 0.5, 0.06}, importantborder=1.5pt,\
                    hmargin={0.7in,0.7in}, vmargin={1in,1in}, verbatimwithframe=true",
    "fontpkg": "",
    "fncychap": r"\usepackage{fncychap}",
    "babel": r"\usepackage[english, russian]{babel}",
    # The font size ('10pt', '11pt' or '12pt').
    #
    "pointsize": "10pt",
    # 'date': '2017, Arenadata™',  # date is setting up by `today` variable, described above
    "preamble": r"""
        \usepackage{indentfirst}  %% It should makes indent at first paragraph in chapter

        \setlength{\parindent}{1cm}

        % Disable 'Continue on the next page'
        \renewcommand{\tablecontinued}[1]{}

        % Disable hyphenation
        \hyphenpenalty10000
        \exhyphenpenalty10000


        \usepackage{amsmath,amsfonts,amssymb,amsthm}
        \usepackage{graphicx}


        \usepackage{color}
        \usepackage{transparent}
        \usepackage{eso-pic}
        \usepackage{lipsum}

        \usepackage{footnotebackref} %%link at the footnote to go to the place of footnote in the text

        %% spacing between line
        \usepackage{setspace}
        \singlespacing


        %%%%%%%%%%% datetime
        \usepackage{datetime}

        %%%%%%%%%%% support charec
        \usepackage[T1]{fontenc}
        \usepackage[utf8]{inputenc}
        \usepackage{newunicodechar}

        \newunicodechar{ẟ}{$\delta$}

        %% RO, LE will not work for 'oneside' layout.
        %% Change oneside to twoside in document class
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}

        %%% Alternating Header for oneside
        \fancyhead[L]{\ifthenelse{\isodd{\value{page}}}{ \small \nouppercase{\leftmark} }{}}
        \fancyhead[R]{\ifthenelse{\isodd{\value{page}}}{}{ \small \nouppercase{\rightmark} }}

        %%% Alternating Header for two side
        %\fancyhead[RO]{\small \nouppercase{\rightmark}}
        %\fancyhead[LE]{\small \nouppercase{\leftmark}}


        %%% page number
        \fancyfoot[RO, RE]{\textbf{\thepage}}

        \renewcommand{\headrulewidth}{0.5pt}
        \renewcommand{\footrulewidth}{0.5pt}

        \renewcommand{\baselinestretch}{1}
    """,
    "maketitle": title,
    "tableofcontents": " ",
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# If true, figures, tables and code-blocks are automatically numbered if they have a caption.
# At same time, the numref role is enabled.
# For now, it works only with the HTML builder and LaTeX builder.
# Default is False.

numfig = True

# The scope of figure numbers, that is, the numfig feature numbers figures in which scope.
# 0 means “whole document”. 1 means “in a section”.
# Sphinx numbers like x.1, x.2, x.3... 2 means “in a subsection”.
# Sphinx numbers like x.x.1, x.x.2, x.x.3..., and so on. Default is 1.

numfig_secnum_depth = 1

# A dictionary mapping 'figure', 'table' and 'code-block' to strings that are used for format of figure numbers.
# Default is to use 'Fig. %s' for 'figure',
# 'Table %s' for 'table' and
# 'Listing %s' for 'code-block'.

numfig_format = {"figure": "Рис. %s.", "table": "Табл. %s.", "code-block": "Лист. %s."}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "Arenadata.tex", "Arenadata Documentation", "Arenadata", "manual"),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "arenadata", "Arenadata Documentation", [author], 1)]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "Arenadata",
        "Arenadata Documentation",
        author,
        "Arenadata",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"https://docs.python.org/": None}

extlinks = {"issue": ("https://arenadata.atlassian.net/browse/%s", "")}


def setup(app):
    app.add_stylesheet("css/theme_custom.css")
    app.add_stylesheet("css/arenadata_comments.css")
    app.add_javascript("js/arenadata_comments.js")
