#!/bin/sh -e

source /etc/adcmenv

waitforwsgi

echo "Run Cron ..."


exec 1>"${adcmlog}/service_cron.out"
exec 2>"${adcmlog}/service_cron.err"
mkdir -p "${adcmvar}/cron/"
exec crond -f -L "${adcmlog}/cron.out" -c "${adcmvar}/cron/"
