upstream django {
    server unix:///adcm/run/adcm.sock;
}


# That variable sets to True if we have non HTTP 200 response.
# That is usefull to disable noise from recurent operations.
map $status $abnormal {
    ~^200  0;
    default 1;
}


server {
    listen      8000;

    include "http.d/proxy.inc";
}
