#!/bin/sh
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /etc/adcmenv

echo "Application initialisation ..."

mkdir -p "${adcmlog}"
exec 1>"${adcmlog}/init.out"
exec 2>"${adcmlog}/init.err"
mkdir -p "${adcmrun}"
mkdir -p "${adcmbundle}"
mkdir -p "${adcmdownload}"
mkdir -p "${adcmfile}"
chmod 700 "${adcmfile}"
mkdir -p "${adcmvar}"
mkdir -p "${adcmtmp}"
chmod 777 "${adcmtmp}"
chmod a+t "${adcmtmp}"
mkdir -p "${adcmuserconf}"
mkdir -p "${adcmlog}/nginx"
ln -s "${adcmlog}/nginx" /var/log/nginx


echo "Root keys generation"
key=/root/.ssh/id_rsa
[ ! -f ${key} ] && ssh-keygen -f ${key} -t rsa -N ""

if [ ! -f "${adcmvar}"/cluster.db ]; then
    echo "Assume first run, generate Django secret key"
    "${adcmroot}"/python/manage.py generate_secret_key "${adcmsecretfile}"
fi

"${adcmroot}"/python/manage.py migrate
"${adcmroot}"/python/init_db.py
"${adcmroot}"/python/backupdb.py
touch "${initreadyfile}"

# That is sleep forever case because I have no idea how to force
# runit to do one time action
exec tail -f /dev/null
